[package]
name = "ort-vault"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
test-support = []

[dependencies]
getrandom.workspace = true
keyring.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
hex.workspace = true

[lints]
workspace = true
