[package]
name = "ort-parser-helper"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ort-parser-runtime = { path = "../ort-parser-runtime" }
ort-documents = { path = "../ort-documents" }

[target.'cfg(unix)'.dependencies]
rustix = { version = "=1.1.4", features = ["process"] }

[build-dependencies]
sha2.workspace = true

[lints]
workspace = true
