[package]
name = "ort-document-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
crc32fast.workspace = true
flate2.workspace = true
hex.workspace = true
ort-documents = { path = "../ort-documents" }
pdfium-render.workspace = true
quick-xml.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
ort-domain = { path = "../ort-domain" }
serde_json.workspace = true
tempfile.workspace = true

[lints]
workspace = true
