// @generated by ort-contract-generator. Do not edit by hand.

import { CONTRACT_VERSION } from "./health";
import { isCommandResponse, type CommandResponse } from "./resume";

export type ExportSource = "saved_draft" | "published_snapshot";
export interface ExportTextRequest {
  contractVersion: typeof CONTRACT_VERSION;
  requestId: string;
  payload: { source: ExportSource; expectedRevision: number };
}
export type ExportTextResult =
  | { status: "cancelled" }
  | {
      status: "exported";
      source: ExportSource;
      revision: number;
      byteCount: number;
      formatVersion: 1;
      cleanupPending: boolean;
      durabilityUnconfirmed: boolean;
    };
export type ExportTextCommandResponse = CommandResponse<ExportTextResult>;
// Separate fixed command: DOCX formatVersion 1 always means plain_docx_v1.
export type ExportDocxRequest = ExportTextRequest;
export type ExportDocxCommandResponse = CommandResponse<ExportTextResult>;
export type ExportFormat = "txt" | "docx";

export function isExportDocxCommandResponse(
  value: unknown,
): value is ExportDocxCommandResponse {
  return isCommandResponse(value, (result): result is ExportTextResult =>
    isExportResult(result, 2097152),
  );
}

export function isExportTextCommandResponse(
  value: unknown,
): value is ExportTextCommandResponse {
  return isCommandResponse(value, (result): result is ExportTextResult =>
    isExportResult(result, 262144),
  );
}

function isExportResult(
  value: unknown,
  maxBytes: number,
): value is ExportTextResult {
  if (typeof value !== "object" || value === null || Array.isArray(value))
    return false;
  const record = value as Record<string, unknown>;
  if (record.status === "cancelled") return Object.keys(record).length === 1;
  return (
    Object.keys(record).length === 7 &&
    record.status === "exported" &&
    (record.source === "saved_draft" ||
      record.source === "published_snapshot") &&
    typeof record.revision === "number" &&
    Number.isSafeInteger(record.revision) &&
    record.revision > 0 &&
    typeof record.byteCount === "number" &&
    Number.isSafeInteger(record.byteCount) &&
    record.byteCount > 0 &&
    record.byteCount <= maxBytes &&
    record.formatVersion === 1 &&
    typeof record.cleanupPending === "boolean" &&
    typeof record.durabilityUnconfirmed === "boolean"
  );
}
