// @generated by ort-contract-generator. Do not edit by hand.

export const CONTRACT_VERSION = 2 as const;

export interface HealthRequest {
  contractVersion: typeof CONTRACT_VERSION;
  requestId: string;
  payload: Record<string, never>;
}

export interface HealthResponse {
  status: "ok";
  appVersion: string;
  profile: "development";
  storageStatus: "development_gated";
  contractVersion: typeof CONTRACT_VERSION;
}

export interface ErrorEnvelope {
  code: string;
  messageKey: string;
  retryable: boolean;
  operationId?: string;
  details: Record<string, unknown>;
}

export type HealthCommandResponse =
  | { ok: true; value: HealthResponse }
  | { ok: false; error: ErrorEnvelope };

export function isHealthCommandResponse(
  value: unknown,
): value is HealthCommandResponse {
  if (!isRecord(value) || typeof value.ok !== "boolean") return false;
  if (value.ok) {
    if (!hasExactKeys(value, ["ok", "value"]) || !isRecord(value.value))
      return false;
    return (
      hasExactKeys(value.value, [
        "status",
        "appVersion",
        "profile",
        "storageStatus",
        "contractVersion",
      ]) &&
      value.value.status === "ok" &&
      typeof value.value.appVersion === "string" &&
      value.value.profile === "development" &&
      value.value.storageStatus === "development_gated" &&
      value.value.contractVersion === CONTRACT_VERSION
    );
  }
  if (!hasExactKeys(value, ["ok", "error"]) || !isRecord(value.error))
    return false;
  const allowedErrorKeys = [
    "code",
    "messageKey",
    "retryable",
    "operationId",
    "details",
  ];
  return (
    hasOnlyKeys(value.error, allowedErrorKeys) &&
    typeof value.error.code === "string" &&
    typeof value.error.messageKey === "string" &&
    typeof value.error.retryable === "boolean" &&
    (value.error.operationId === undefined ||
      typeof value.error.operationId === "string") &&
    isRecord(value.error.details)
  );
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hasExactKeys(value: Record<string, unknown>, keys: string[]): boolean {
  return hasOnlyKeys(value, keys) && Object.keys(value).length === keys.length;
}

function hasOnlyKeys(value: Record<string, unknown>, keys: string[]): boolean {
  return Object.keys(value).every((key) => keys.includes(key));
}
