// @generated by ort-contract-generator. Do not edit by hand.
// Decision payload only; not a command, session credential or source envelope.
export type ImportSectionTarget =
  | { kind: "new" }
  | { kind: "existing"; id: string };
export type ImportTextTarget =
  | { kind: "proposed"; index: number }
  | { kind: "existing"; id: string }
  | { kind: "new"; heading: string };
export type ImportChoice =
  | { kind: "pending" }
  | { kind: "reject" }
  | { kind: "section"; heading: string; target: ImportSectionTarget }
  | {
      kind: "contact";
      field: "fullName" | "email" | "phone" | "location";
      value: string;
      mode: "fillEmpty" | "replace" | "keepExisting";
    }
  | { kind: "text"; text: string; bullet: boolean; target: ImportTextTarget };
export interface ImportChoices {
  choices: ImportChoice[];
}

export interface ImportReviewRequest {
  contractVersion: number;
  requestId: string;
  payload: { reviewId: string };
}
export interface ApplyImportReviewRequest {
  contractVersion: number;
  requestId: string;
  payload: { reviewId: string; decisionsJson: string };
}

export interface ImportReviewSnapshot {
  id: string;
  baseRevision: number;
  mappingVersion: 1;
  blocks: {
    source: string;
    page: number;
    explanation: string;
    suggestedTarget:
      | "section"
      | "text"
      | "bullet"
      | "fullName"
      | "email"
      | "phone"
      | "location";
    suggestedValue: string;
    proposedSection: number | null;
  }[];
  sections: { id: string; heading: string }[];
  contacts: {
    fullName: string;
    email: string;
    phone: string;
    location: string;
  };
}
export function isImportReviewSnapshot(
  value: unknown,
): value is ImportReviewSnapshot {
  const object = (
    value: unknown,
    keys: string[],
  ): value is Record<string, unknown> =>
    typeof value === "object" &&
    value !== null &&
    !Array.isArray(value) &&
    Object.keys(value).length === keys.length &&
    keys.every((key) => Object.hasOwn(value, key));
  const uuid = (value: unknown): value is string =>
    typeof value === "string" &&
    /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(
      value,
    );
  let total = 0;
  const text = (value: unknown, max: number): value is string => {
    if (typeof value !== "string" || value.length > max * 2) return false;
    let count = 0;
    for (const c of value) {
      const n = c.codePointAt(0)!;
      if (
        (n < 32 && ![9, 10, 13].includes(n)) ||
        (n >= 127 && n <= 159) ||
        (n >= 0xd800 && n <= 0xdfff)
      )
        return false;
      count++;
    }
    total += count;
    return count <= max && total <= 250000;
  };
  if (
    !object(value, [
      "id",
      "baseRevision",
      "mappingVersion",
      "blocks",
      "sections",
      "contacts",
    ]) ||
    !uuid(value.id) ||
    !Number.isSafeInteger(value.baseRevision) ||
    (value.baseRevision as number) < 0 ||
    value.mappingVersion !== 1 ||
    !Array.isArray(value.blocks) ||
    value.blocks.length > 1000 ||
    value.blocks.length === 0 ||
    !Array.isArray(value.sections) ||
    value.sections.length > 100 ||
    !object(value.contacts, ["fullName", "email", "phone", "location"])
  )
    return false;
  if (!Object.values(value.contacts).every((v) => text(v, 100000)))
    return false;
  const ids = new Set<string>();
  if (
    !value.sections.every((section) => {
      if (
        !object(section, ["id", "heading"]) ||
        !uuid(section.id) ||
        ids.has(section.id) ||
        !text(section.heading, 100000)
      )
        return false;
      ids.add(section.id);
      return true;
    })
  )
    return false;
  const blocks = value.blocks;
  let sourceCharacters = 0;
  return value.blocks.every((block, index) => {
    if (
      !object(block, [
        "source",
        "page",
        "explanation",
        "suggestedTarget",
        "suggestedValue",
        "proposedSection",
      ]) ||
      !text(block.source, 30000) ||
      !text(block.suggestedValue, 30000) ||
      !text(block.explanation, 1000) ||
      !Number.isInteger(block.page) ||
      (block.page as number) < 1 ||
      (block.page as number) > 10 ||
      ![
        "section",
        "text",
        "bullet",
        "fullName",
        "email",
        "phone",
        "location",
      ].includes(block.suggestedTarget as string)
    )
      return false;
    sourceCharacters += Array.from(block.source).length;
    const target = block.proposedSection;
    return (
      sourceCharacters <= 50000 &&
      (target === null ||
        (Number.isInteger(target) &&
          (target as number) >= 0 &&
          (target as number) < index &&
          blocks[target as number]?.suggestedTarget === "section"))
    );
  });
}

export interface BeginImportRequest {
  contractVersion: number;
  requestId: string;
  payload: { expectedRevision: number | null };
}
