// @generated by ort-contract-generator. Do not edit by hand.

import { CONTRACT_VERSION } from "./health";
import { isCommandResponse, type CommandResponse } from "./resume";

export interface CloseStatus {
  pendingAttempt: string | null;
}

export type CloseDecision = "cancel" | "quit";

export interface ResolveCloseRequest {
  contractVersion: typeof CONTRACT_VERSION;
  requestId: string;
  payload: { attempt: string; decision: CloseDecision };
}

export type CloseCommandResponse = CommandResponse<CloseStatus>;

export function isCloseCommandResponse(
  value: unknown,
): value is CloseCommandResponse {
  return isCommandResponse(value, isCloseStatus);
}

function isCloseStatus(value: unknown): value is CloseStatus {
  if (typeof value !== "object" || value === null || Array.isArray(value))
    return false;
  const record = value as Record<string, unknown>;
  return (
    Object.keys(record).length === 1 &&
    "pendingAttempt" in record &&
    (record.pendingAttempt === null ||
      (typeof record.pendingAttempt === "string" &&
        /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(
          record.pendingAttempt,
        )))
  );
}
