use std::{fs, path::PathBuf};

use ort_domain::{
    BackupRecoveryStatusRequest, BackupRecoveryStatusResponse, CloseStatusRequest,
    CloseStatusResponse, DeleteAllLocalDataRequest, DeleteAllLocalDataResponse,
    DeleteSafetyCopyRequest, DeleteSafetyCopyResponse, DocumentLimits, ExportBackupRequest,
    ExportBackupResponse, ExportDocxRequest, ExportDocxResponse, ExportTextRequest,
    ExportTextResponse, HealthRequest, HealthResponse, LoadResumeRequest, PublishResumeRequest,
    PublishResumeResponse, ResolveCloseRequest, RestoreBackupRequest, RestoreBackupResponse,
    ResumeWorkspaceResponse, RollbackSafetyCopyRequest, RollbackSafetyCopyResponse,
    SaveResumeRequest, StorageUsageRequest, StorageUsageResponse, ValidateBackupRequest,
    ValidateBackupResponse, VersionedResumeResponse,
};
use schemars::schema_for;

const TYPESCRIPT: &str = include_str!("health.ts.template");
const RESUME_TYPESCRIPT: &str = include_str!("resume.ts.template");
const COMPATIBILITY: &str = include_str!("compatibility.json.template");

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let root = workspace_root()?;
    let output = root.join("packages/contracts/generated");
    fs::create_dir_all(&output)?;
    write_backup_contracts(&output)?;
    write_schema::<ExportTextRequest>(&output.join("export.text.request.schema.json"))?;
    write_schema::<ExportTextResponse>(&output.join("export.text.response.schema.json"))?;
    write_schema::<ExportDocxRequest>(&output.join("export.docx.request.schema.json"))?;
    write_schema::<ExportDocxResponse>(&output.join("export.docx.response.schema.json"))?;
    fs::write(output.join("export.ts"), include_str!("export.ts.template"))?;

    write_pdf_contracts(&output)?;

    write_schema::<HealthRequest>(&output.join("health.request.schema.json"))?;
    write_schema::<HealthResponse>(&output.join("health.response.schema.json"))?;
    write_schema::<LoadResumeRequest>(&output.join("resume.load.request.schema.json"))?;
    write_schema::<SaveResumeRequest>(&output.join("resume.save.request.schema.json"))?;
    write_schema::<PublishResumeRequest>(&output.join("resume.publish.request.schema.json"))?;
    write_schema::<ResumeWorkspaceResponse>(&output.join("resume.workspace.response.schema.json"))?;
    write_schema::<VersionedResumeResponse>(&output.join("resume.versioned.response.schema.json"))?;
    write_schema::<PublishResumeResponse>(&output.join("resume.publish.response.schema.json"))?;
    write_schema::<CloseStatusRequest>(&output.join("lifecycle.status.request.schema.json"))?;
    write_schema::<CloseStatusResponse>(&output.join("lifecycle.status.response.schema.json"))?;
    write_schema::<ResolveCloseRequest>(&output.join("lifecycle.resolve.request.schema.json"))?;
    fs::write(
        output.join("lifecycle.ts"),
        include_str!("lifecycle.ts.template"),
    )?;
    fs::write(output.join("health.ts"), TYPESCRIPT)?;
    fs::write(output.join("resume.ts"), RESUME_TYPESCRIPT)?;
    write_schema::<StorageUsageRequest>(&output.join("storage.usage.request.schema.json"))?;
    write_schema::<StorageUsageResponse>(&output.join("storage.usage.response.schema.json"))?;
    write_schema::<DeleteAllLocalDataRequest>(
        &output.join("storage.delete-all.request.schema.json"),
    )?;
    write_schema::<DeleteAllLocalDataResponse>(
        &output.join("storage.delete-all.response.schema.json"),
    )?;
    fs::write(
        output.join("storage.ts"),
        include_str!("storage.ts.template").replace(
            "__DELETE_ALL_CONFIRMATION_PHRASE__",
            ort_domain::DELETE_ALL_LOCAL_DATA_CONFIRMATION_PHRASE,
        ),
    )?;
    let limits = DocumentLimits::default();
    fs::write(
        output.join("limits.ts"),
        format!(
            "// @generated by ort-contract-generator. Do not edit by hand.\n\nexport const DOCUMENT_LIMITS = {{\n  totalCharacters: {},\n  sections: {},\n  entries: {},\n  bullets: {},\n  links: {},\n  skills: {},\n  fieldCharacters: {},\n  bulletCharacters: {},\n  serializedBytes: {},\n}} as const;\n",
            limits.total_characters,
            limits.sections,
            limits.entries,
            limits.bullets,
            limits.links,
            limits.skills,
            limits.field_characters,
            limits.bullet_characters,
            limits.serialized_bytes,
        ),
    )?;
    fs::write(output.join("compatibility.json"), COMPATIBILITY)?;

    println!("Generated development contracts in {}", output.display());
    Ok(())
}

fn write_pdf_contracts(output: &std::path::Path) -> Result<(), Box<dyn std::error::Error>> {
    write_schema::<ort_domain::RenderPdfRequest>(&output.join("pdf.render.request.schema.json"))?;
    write_schema::<ort_domain::PdfPreviewResponse>(
        &output.join("pdf.preview.response.schema.json"),
    )?;
    write_schema::<ort_domain::PdfTicketRequest>(&output.join("pdf.ticket.request.schema.json"))?;
    write_schema::<ort_domain::PdfExportResponse>(&output.join("pdf.export.response.schema.json"))?;
    write_schema::<ort_domain::PdfReleaseResponse>(
        &output.join("pdf.release.response.schema.json"),
    )?;
    write_schema::<ort_domain::PdfRenderHistoryRequest>(
        &output.join("pdf.history.request.schema.json"),
    )?;
    write_schema::<ort_domain::PdfRenderHistoryResponse>(
        &output.join("pdf.history.response.schema.json"),
    )?;
    write_schema::<ort_domain::PdfReplayRequest>(&output.join("pdf.replay.request.schema.json"))?;
    write_schema::<ort_domain::PdfReplayResponse>(&output.join("pdf.replay.response.schema.json"))?;
    write_schema::<ort_domain::OpenPortablePdfHistoryRequest>(
        &output.join("pdf.portable-history.request.schema.json"),
    )?;
    write_schema::<ort_domain::PortablePdfHistoryResponse>(
        &output.join("pdf.portable-history.response.schema.json"),
    )?;
    write_schema::<ort_domain::PortablePdfReplayRequest>(
        &output.join("pdf.portable-replay.request.schema.json"),
    )?;
    write_schema::<ort_domain::PortablePdfArchiveRequest>(
        &output.join("pdf.portable-release.request.schema.json"),
    )?;
    write_schema::<ort_domain::PortablePdfArchiveReleaseResponse>(
        &output.join("pdf.portable-release.response.schema.json"),
    )?;
    fs::write(
        output.join("pdf.ts"),
        include_str!("pdf.ts.template")
            .replace("__MAX_PDF_BYTES__", &ort_domain::MAX_PDF_BYTES.to_string())
            .replace("__MAX_PDF_PAGES__", &ort_domain::MAX_PDF_PAGES.to_string())
            .replace(
                "__MAX_PDF_RENDER_HISTORY__",
                &ort_domain::MAX_PDF_RENDER_HISTORY.to_string(),
            )
            .replace(
                "__PDF_TTL__",
                &ort_domain::PDF_PREVIEW_TTL_SECONDS.to_string(),
            ),
    )?;
    Ok(())
}

fn write_backup_contracts(output: &std::path::Path) -> Result<(), Box<dyn std::error::Error>> {
    write_schema::<ExportBackupRequest>(&output.join("backup.export.request.schema.json"))?;
    write_schema::<ExportBackupResponse>(&output.join("backup.export.response.schema.json"))?;
    write_schema::<ValidateBackupRequest>(&output.join("backup.validate.request.schema.json"))?;
    write_schema::<ValidateBackupResponse>(&output.join("backup.validate.response.schema.json"))?;
    write_schema::<RestoreBackupRequest>(&output.join("backup.restore.request.schema.json"))?;
    write_schema::<RestoreBackupResponse>(&output.join("backup.restore.response.schema.json"))?;
    write_schema::<BackupRecoveryStatusRequest>(
        &output.join("backup.recovery-status.request.schema.json"),
    )?;
    write_schema::<BackupRecoveryStatusResponse>(
        &output.join("backup.recovery-status.response.schema.json"),
    )?;
    write_schema::<RollbackSafetyCopyRequest>(&output.join("backup.rollback.request.schema.json"))?;
    write_schema::<RollbackSafetyCopyResponse>(
        &output.join("backup.rollback.response.schema.json"),
    )?;
    write_schema::<DeleteSafetyCopyRequest>(
        &output.join("backup.safety-delete.request.schema.json"),
    )?;
    write_schema::<DeleteSafetyCopyResponse>(
        &output.join("backup.safety-delete.response.schema.json"),
    )?;
    fs::write(
        output.join("backup.ts"),
        include_str!("backup.ts.template")
            .replace(
                "__MAX_BACKUP_BYTES__",
                &ort_domain::MAX_BACKUP_BYTES.to_string(),
            )
            .replace(
                "__MAX_BACKUP_PASSPHRASE_BYTES__",
                &ort_domain::MAX_BACKUP_PASSPHRASE_BYTES.to_string(),
            )
            .replace(
                "__RESTORE_CONFIRMATION_PHRASE__",
                ort_domain::RESTORE_CONFIRMATION_PHRASE,
            )
            .replace(
                "__ROLLBACK_CONFIRMATION_PHRASE__",
                ort_domain::ROLLBACK_CONFIRMATION_PHRASE,
            )
            .replace(
                "__DELETE_SAFETY_CONFIRMATION_PHRASE__",
                ort_domain::DELETE_SAFETY_CONFIRMATION_PHRASE,
            ),
    )?;
    Ok(())
}

fn write_schema<T: schemars::JsonSchema>(
    destination: &std::path::Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let schema = schema_for!(T);
    let schema_json = format!("{}\n", serde_json::to_string_pretty(&schema)?);
    fs::write(destination, schema_json)?;
    Ok(())
}

fn workspace_root() -> Result<PathBuf, Box<dyn std::error::Error>> {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(std::path::Path::parent)
        .map(PathBuf::from)
        .ok_or_else(|| "contract generator is not inside the workspace".into())
}
