// @generated by ort-contract-generator. Do not edit by hand.

import { CONTRACT_VERSION, type ErrorEnvelope } from "./health";

export { CONTRACT_VERSION };

export interface Link {
  label: string;
  url: string;
}

export interface ContactDetails {
  fullName: string;
  email: string;
  phone: string;
  location: string;
  links: Link[];
}

export interface NamedField {
  id: string;
  order: number;
  label: string;
  value: string;
  isSkill: boolean;
}

export interface Bullet {
  id: string;
  order: number;
  text: string;
}

export interface ResumeEntry {
  id: string;
  order: number;
  heading: string;
  subheading: string;
  dateRange: string;
  location: string;
  fields: NamedField[];
  bullets: Bullet[];
  links: Link[];
}

export interface ResumeSection {
  id: string;
  order: number;
  heading: string;
  entries: ResumeEntry[];
}

export interface ResumeDocument {
  schemaVersion: number;
  documentId: string;
  title: string;
  contact: ContactDetails;
  sections: ResumeSection[];
}

export interface VersionedResume {
  revision: number;
  document: ResumeDocument;
}

export interface ResumeWorkspace {
  draft: VersionedResume | null;
  latestPublished: VersionedResume | null;
}

export interface PublishResumeResponse {
  draftRevision: number;
  published: VersionedResume;
}

export interface LoadResumeRequest {
  contractVersion: typeof CONTRACT_VERSION;
  requestId: string;
  payload: Record<string, never>;
}

export interface SaveResumeRequest {
  contractVersion: typeof CONTRACT_VERSION;
  requestId: string;
  payload: {
    expectedRevision: number | null;
    document: ResumeDocument;
  };
}

export interface PublishResumeRequest {
  contractVersion: typeof CONTRACT_VERSION;
  requestId: string;
  payload: { expectedDraftRevision: number };
}

export type CommandResponse<T> =
  | { ok: true; value: T }
  | { ok: false; error: ErrorEnvelope };

export type ResumeWorkspaceCommandResponse = CommandResponse<ResumeWorkspace>;
export type VersionedResumeCommandResponse = CommandResponse<VersionedResume>;
export type PublishResumeCommandResponse =
  CommandResponse<PublishResumeResponse>;

export function isResumeWorkspaceCommandResponse(
  value: unknown,
): value is ResumeWorkspaceCommandResponse {
  return isCommandResponse(value, isResumeWorkspace);
}

export function isVersionedResumeCommandResponse(
  value: unknown,
): value is VersionedResumeCommandResponse {
  return isCommandResponse(value, isVersionedResume);
}

export function isPublishResumeCommandResponse(
  value: unknown,
): value is PublishResumeCommandResponse {
  return isCommandResponse(value, isPublishResumeResponse);
}

function isCommandResponse<T>(
  value: unknown,
  isValue: (candidate: unknown) => candidate is T,
): value is CommandResponse<T> {
  if (!isRecord(value) || typeof value.ok !== "boolean") return false;
  if (value.ok) {
    return hasExactKeys(value, ["ok", "value"]) && isValue(value.value);
  }
  return hasExactKeys(value, ["ok", "error"]) && isErrorEnvelope(value.error);
}

function isResumeWorkspace(value: unknown): value is ResumeWorkspace {
  return (
    isRecord(value) &&
    hasExactKeys(value, ["draft", "latestPublished"]) &&
    (value.draft === null || isVersionedResume(value.draft)) &&
    (value.latestPublished === null || isVersionedResume(value.latestPublished))
  );
}

function isPublishResumeResponse(
  value: unknown,
): value is PublishResumeResponse {
  return (
    isRecord(value) &&
    hasExactKeys(value, ["draftRevision", "published"]) &&
    isPositiveInteger(value.draftRevision) &&
    isVersionedResume(value.published)
  );
}

function isVersionedResume(value: unknown): value is VersionedResume {
  return (
    isRecord(value) &&
    hasExactKeys(value, ["revision", "document"]) &&
    isPositiveInteger(value.revision) &&
    isResumeDocument(value.document)
  );
}

function isResumeDocument(value: unknown): value is ResumeDocument {
  return (
    isRecord(value) &&
    hasExactKeys(value, [
      "schemaVersion",
      "documentId",
      "title",
      "contact",
      "sections",
    ]) &&
    value.schemaVersion === 1 &&
    typeof value.documentId === "string" &&
    typeof value.title === "string" &&
    isContactDetails(value.contact) &&
    Array.isArray(value.sections) &&
    value.sections.every(isResumeSection)
  );
}

function isContactDetails(value: unknown): value is ContactDetails {
  return (
    isRecord(value) &&
    hasExactKeys(value, ["fullName", "email", "phone", "location", "links"]) &&
    typeof value.fullName === "string" &&
    typeof value.email === "string" &&
    typeof value.phone === "string" &&
    typeof value.location === "string" &&
    Array.isArray(value.links) &&
    value.links.every(isLink)
  );
}

function isResumeSection(value: unknown): value is ResumeSection {
  return (
    isRecord(value) &&
    hasExactKeys(value, ["id", "order", "heading", "entries"]) &&
    typeof value.id === "string" &&
    isNonNegativeInteger(value.order) &&
    typeof value.heading === "string" &&
    Array.isArray(value.entries) &&
    value.entries.every(isResumeEntry)
  );
}

function isResumeEntry(value: unknown): value is ResumeEntry {
  return (
    isRecord(value) &&
    hasExactKeys(value, [
      "id",
      "order",
      "heading",
      "subheading",
      "dateRange",
      "location",
      "fields",
      "bullets",
      "links",
    ]) &&
    typeof value.id === "string" &&
    isNonNegativeInteger(value.order) &&
    typeof value.heading === "string" &&
    typeof value.subheading === "string" &&
    typeof value.dateRange === "string" &&
    typeof value.location === "string" &&
    Array.isArray(value.fields) &&
    value.fields.every(isNamedField) &&
    Array.isArray(value.bullets) &&
    value.bullets.every(isBullet) &&
    Array.isArray(value.links) &&
    value.links.every(isLink)
  );
}

function isNamedField(value: unknown): value is NamedField {
  return (
    isRecord(value) &&
    hasExactKeys(value, ["id", "order", "label", "value", "isSkill"]) &&
    typeof value.id === "string" &&
    isNonNegativeInteger(value.order) &&
    typeof value.label === "string" &&
    typeof value.value === "string" &&
    typeof value.isSkill === "boolean"
  );
}

function isBullet(value: unknown): value is Bullet {
  return (
    isRecord(value) &&
    hasExactKeys(value, ["id", "order", "text"]) &&
    typeof value.id === "string" &&
    isNonNegativeInteger(value.order) &&
    typeof value.text === "string"
  );
}

function isLink(value: unknown): value is Link {
  return (
    isRecord(value) &&
    hasExactKeys(value, ["label", "url"]) &&
    typeof value.label === "string" &&
    typeof value.url === "string"
  );
}

function isErrorEnvelope(value: unknown): value is ErrorEnvelope {
  if (!isRecord(value)) return false;
  const allowed = ["code", "messageKey", "retryable", "operationId", "details"];
  return (
    hasOnlyKeys(value, allowed) &&
    typeof value.code === "string" &&
    typeof value.messageKey === "string" &&
    typeof value.retryable === "boolean" &&
    (value.operationId === undefined ||
      typeof value.operationId === "string") &&
    isRecord(value.details)
  );
}

function isPositiveInteger(value: unknown): value is number {
  return Number.isInteger(value) && (value as number) >= 1;
}

function isNonNegativeInteger(value: unknown): value is number {
  return Number.isInteger(value) && (value as number) >= 0;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hasExactKeys(value: Record<string, unknown>, keys: string[]): boolean {
  return hasOnlyKeys(value, keys) && Object.keys(value).length === keys.length;
}

function hasOnlyKeys(value: Record<string, unknown>, keys: string[]): boolean {
  return Object.keys(value).every((key) => keys.includes(key));
}
