// @generated by ort-contract-generator. Do not edit by hand.
import wire from "./wire.schema.json";
import type { DesktopCommands } from "./wire";

type Schema = boolean | { [key: string]: unknown };
const definitions: Record<string, Schema> = wire.$defs;
const record = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

/** Decode the generated schema without promoting an unchecked IPC assertion. */
export function matchesSchema(value: unknown, schema: Schema): boolean {
  let remaining = 500_000;
  function match(value: unknown, schema: Schema, depth: number): boolean {
    if (--remaining < 0 || depth > 128) return false;
    if (typeof schema === "boolean") return schema;
    if (typeof schema.$ref === "string") {
      const referenced = definitions[schema.$ref.replace("#/$defs/", "")];
      return referenced !== undefined && match(value, referenced, depth + 1);
    }
    if ("const" in schema && value !== schema.const) return false;
    if (Array.isArray(schema.enum) && !schema.enum.includes(value))
      return false;
    for (const key of ["anyOf", "oneOf", "allOf"] as const) {
      const variants = schema[key];
      if (!Array.isArray(variants)) continue;
      const matches = variants.filter((variant) =>
        match(value, variant, depth + 1),
      ).length;
      if (
        (key === "anyOf" && matches === 0) ||
        (key === "oneOf" && matches !== 1) ||
        (key === "allOf" && matches !== variants.length)
      )
        return false;
    }
    if (Array.isArray(schema.type)) {
      return schema.type.some((type) =>
        match(value, { ...schema, type }, depth + 1),
      );
    }
    switch (schema.type) {
      case "null":
        return value === null;
      case "boolean":
        return typeof value === "boolean";
      case "string": {
        if (typeof value !== "string") return false;
        if (
          schema.format === "uuid" &&
          !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(
            value,
          )
        )
          return false;
        if (
          typeof schema.minLength === "number" &&
          [...value].length < schema.minLength
        )
          return false;
        if (
          typeof schema.maxLength === "number" &&
          [...value].length > schema.maxLength
        )
          return false;
        return (
          typeof schema.pattern !== "string" ||
          new RegExp(schema.pattern, "u").test(value)
        );
      }
      case "integer":
      case "number":
        return (
          typeof value === "number" &&
          Number.isFinite(value) &&
          (schema.type !== "integer" || Number.isSafeInteger(value)) &&
          (typeof schema.minimum !== "number" || value >= schema.minimum) &&
          (typeof schema.maximum !== "number" || value <= schema.maximum)
        );
      case "array":
        return (
          Array.isArray(value) &&
          (typeof schema.minItems !== "number" ||
            value.length >= schema.minItems) &&
          (typeof schema.maxItems !== "number" ||
            value.length <= schema.maxItems) &&
          value.every((item) =>
            match(item, (schema.items ?? true) as Schema, depth + 1),
          )
        );
      case "object": {
        if (!record(value)) return false;
        const properties = (schema.properties ?? {}) as Record<string, Schema>;
        if (
          Array.isArray(schema.required) &&
          schema.required.some(
            (name) => typeof name !== "string" || !Object.hasOwn(value, name),
          )
        )
          return false;
        return Object.entries(value).every(([name, item]) =>
          match(
            item,
            Object.hasOwn(properties, name)
              ? properties[name]
              : ((schema.additionalProperties ?? true) as Schema),
            depth + 1,
          ),
        );
      }
      default:
        return true;
    }
  }
  return match(value, schema, 0);
}

export function isDesktopValue<K extends keyof DesktopCommands>(
  command: K,
  value: unknown,
): value is DesktopCommands[K]["value"] {
  return matchesSchema(value, wire.commands[command].value);
}
