[package]
name = "ort-contract-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ort-desktop = { path = "../../apps/desktop/src-tauri" }
syn = { version = "=2.0.119", features = ["full"] }
ort-backup = { path = "../ort-backup" }
ort-domain = { path = "../ort-domain" }
schemars.workspace = true
serde_json.workspace = true

[lints]
workspace = true
