[package]
name = "ort-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ort-domain = { path = "../ort-domain" }
ort-documents = { path = "../ort-documents" }
typst.workspace = true
typst-pdf.workspace = true
typst-layout.workspace = true
typst-assets.workspace = true
comemo.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
thiserror.workspace = true

[lints]
workspace = true
