use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::{ErrorEnvelope, ExportSource, ExportTextRequest, validate_request_metadata};

// Protective development limits, deliberately below the product's 20 MiB ceiling.
pub const MAX_PDF_BYTES: usize = 4 * 1024 * 1024;
pub const MAX_PDF_PAGES: usize = 5;
pub const PDF_PREVIEW_TTL_SECONDS: u64 = 600;

pub type RenderPdfRequest = ExportTextRequest;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfRenderReceipt {
    pub document_sha256: String,
    pub document_schema_version: u16,
    pub pdf_sha256: String,
    pub renderer_version: String,
    pub template_id: String,
    pub template_sha256: String,
    pub font_bundle_id: String,
    pub font_bundle_sha256: String,
    pub page_count: usize,
    pub byte_count: usize,
}

#[derive(Clone, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfPreviewResponse {
    pub render_id: String,
    pub source: ExportSource,
    pub revision: i64,
    pub generated_at_unix_ms: u64,
    pub receipt: PdfRenderReceipt,
    // Bounded generated bytes only; no renderer-supplied PDF ever enters Rust.
    pub pdf_base64: String,
}

#[derive(Debug, Clone, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfTicketPayload {
    pub render_id: String,
}

#[derive(Debug, Clone, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfTicketRequest {
    pub contract_version: u16,
    pub request_id: String,
    pub payload: PdfTicketPayload,
}

impl PdfTicketRequest {
    /// # Errors
    /// Rejects noncanonical IDs and metadata before accessing a preview or dialog.
    pub fn validate(&self) -> Result<(), ErrorEnvelope> {
        validate_request_metadata(self.contract_version, &self.request_id)?;
        let parsed = uuid::Uuid::parse_str(&self.payload.render_id).ok();
        if !parsed
            .is_some_and(|id| id.get_version_num() == 7 && id.to_string() == self.payload.render_id)
        {
            return Err(ErrorEnvelope::new(
                "INVALID_RENDER_ID",
                "errors.invalidRenderId",
                false,
            ));
        }
        Ok(())
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "status", rename_all = "snake_case", deny_unknown_fields)]
pub enum PdfExportResponse {
    Cancelled,
    #[serde(rename_all = "camelCase")]
    Exported {
        render_id: String,
        pdf_sha256: String,
        byte_count: usize,
        cleanup_pending: bool,
        durability_unconfirmed: bool,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfReleaseResponse {
    pub released: bool,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    #[test]
    fn only_canonical_v7_tickets_and_known_fields_cross_the_boundary() {
        let id = "019abcde-abcd-7abc-8abc-abcdef012345".to_owned();
        let valid = json!({"contractVersion": crate::CONTRACT_VERSION, "requestId": "synthetic-pdf", "payload": {"renderId": id}});
        assert!(
            serde_json::from_value::<PdfTicketRequest>(valid.clone())
                .unwrap()
                .validate()
                .is_ok()
        );
        for id in [
            "../path".into(),
            id.to_uppercase(),
            "00000000-0000-4000-8000-000000000000".into(),
            String::new(),
        ] {
            let mut bad = valid.clone();
            bad["payload"]["renderId"] = json!(id);
            assert!(
                serde_json::from_value::<PdfTicketRequest>(bad)
                    .unwrap()
                    .validate()
                    .is_err()
            );
        }
        for key in ["path", "pdfBase64", "overwrite", "template", "source"] {
            let mut bad = valid.clone();
            bad["payload"][key] = json!("untrusted");
            assert!(serde_json::from_value::<PdfTicketRequest>(bad).is_err());
        }
    }
}
