use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::{
    EmptyPayload, ErrorEnvelope, ExportSource, ExportTextRequest, validate_request_metadata,
};

// Protective development limits, deliberately below the product's 20 MiB ceiling.
pub const MAX_PDF_BYTES: usize = 4 * 1024 * 1024;
pub const MAX_PDF_PAGES: usize = 5;
pub const PDF_PREVIEW_TTL_SECONDS: u64 = 600;
pub const MAX_PDF_RENDER_HISTORY: u16 = 20;

pub type RenderPdfRequest = ExportTextRequest;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfRenderReceipt {
    pub document_sha256: String,
    pub document_schema_version: u16,
    pub pdf_sha256: String,
    pub renderer_version: String,
    pub template_id: String,
    pub template_sha256: String,
    pub font_bundle_id: String,
    pub font_bundle_sha256: String,
    pub page_count: usize,
    pub byte_count: usize,
}

#[derive(Clone, Serialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfPreviewResponse {
    pub render_id: String,
    pub source: ExportSource,
    pub revision: i64,
    pub generated_at_unix_ms: u64,
    pub receipt: PdfRenderReceipt,
    // Bounded generated bytes only; no renderer-supplied PDF ever enters Rust.
    pub pdf_base64: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfRenderManifest {
    pub manifest_id: String,
    pub source: ExportSource,
    pub source_revision: i64,
    pub generated_at_unix_ms: u64,
    pub last_generated_at_unix_ms: u64,
    pub render_count: u32,
    pub receipt: PdfRenderReceipt,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfRenderHistoryResponse {
    pub manifests: Vec<PdfRenderManifest>,
}

#[derive(Debug, Clone, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfRenderHistoryRequest {
    pub contract_version: u16,
    pub request_id: String,
    pub payload: EmptyPayload,
}

#[derive(Debug, Clone, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfReplayPayload {
    pub manifest_id: String,
}

#[derive(Debug, Clone, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfReplayRequest {
    pub contract_version: u16,
    pub request_id: String,
    pub payload: PdfReplayPayload,
}

impl PdfReplayRequest {
    /// # Errors
    /// Rejects noncanonical manifest IDs and metadata before storage access.
    pub fn validate(&self) -> Result<(), ErrorEnvelope> {
        validate_request_metadata(self.contract_version, &self.request_id)?;
        validate_v7_id(&self.payload.manifest_id, "INVALID_RENDER_MANIFEST_ID")
    }
}

impl PdfRenderHistoryRequest {
    /// # Errors
    /// Rejects unsupported or malformed command metadata.
    pub fn validate(&self) -> Result<(), ErrorEnvelope> {
        validate_request_metadata(self.contract_version, &self.request_id)
    }
}

#[derive(Debug, Clone, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfTicketPayload {
    pub render_id: String,
}

#[derive(Debug, Clone, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfTicketRequest {
    pub contract_version: u16,
    pub request_id: String,
    pub payload: PdfTicketPayload,
}

impl PdfTicketRequest {
    /// # Errors
    /// Rejects noncanonical IDs and metadata before accessing a preview or dialog.
    pub fn validate(&self) -> Result<(), ErrorEnvelope> {
        validate_request_metadata(self.contract_version, &self.request_id)?;
        validate_v7_id(&self.payload.render_id, "INVALID_RENDER_ID")
    }
}

fn validate_v7_id(value: &str, code: &str) -> Result<(), ErrorEnvelope> {
    let parsed = uuid::Uuid::parse_str(value).ok();
    if parsed.is_some_and(|id| id.get_version_num() == 7 && id.to_string() == value) {
        Ok(())
    } else {
        Err(ErrorEnvelope::new(code, "errors.invalidRenderId", false))
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "status", rename_all = "snake_case", deny_unknown_fields)]
pub enum PdfExportResponse {
    Cancelled,
    #[serde(rename_all = "camelCase")]
    Exported {
        render_id: String,
        pdf_sha256: String,
        byte_count: usize,
        cleanup_pending: bool,
        durability_unconfirmed: bool,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PdfReleaseResponse {
    pub released: bool,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    #[test]
    fn only_canonical_v7_tickets_and_known_fields_cross_the_boundary() {
        let id = "019abcde-abcd-7abc-8abc-abcdef012345".to_owned();
        let valid = json!({"contractVersion": crate::CONTRACT_VERSION, "requestId": "synthetic-pdf", "payload": {"renderId": id}});
        assert!(
            serde_json::from_value::<PdfTicketRequest>(valid.clone())
                .unwrap()
                .validate()
                .is_ok()
        );
        for id in [
            "../path".into(),
            id.to_uppercase(),
            "00000000-0000-4000-8000-000000000000".into(),
            String::new(),
        ] {
            let mut bad = valid.clone();
            bad["payload"]["renderId"] = json!(id);
            assert!(
                serde_json::from_value::<PdfTicketRequest>(bad)
                    .unwrap()
                    .validate()
                    .is_err()
            );
        }
        for key in ["path", "pdfBase64", "overwrite", "template", "source"] {
            let mut bad = valid.clone();
            bad["payload"][key] = json!("untrusted");
            assert!(serde_json::from_value::<PdfTicketRequest>(bad).is_err());
        }
    }

    #[test]
    fn replay_accepts_only_a_canonical_manifest_identity() {
        let valid = serde_json::json!({
            "contractVersion": crate::CONTRACT_VERSION,
            "requestId": "synthetic-replay",
            "payload": {"manifestId": "019abcde-abcd-7abc-8abc-abcdef012345"}
        });
        assert!(
            serde_json::from_value::<PdfReplayRequest>(valid.clone())
                .unwrap()
                .validate()
                .is_ok()
        );
        for value in ["../manifest", "00000000-0000-4000-8000-000000000000"] {
            let mut invalid = valid.clone();
            invalid["payload"]["manifestId"] = serde_json::json!(value);
            assert!(
                serde_json::from_value::<PdfReplayRequest>(invalid)
                    .unwrap()
                    .validate()
                    .is_err()
            );
        }
        let mut extra = valid;
        extra["payload"]["source"] = serde_json::json!("saved_draft");
        assert!(serde_json::from_value::<PdfReplayRequest>(extra).is_err());
    }
}
