/* Review-only artwork. Navigation switches synthetic mockups; no native commands,
   provider requests, credentials, local-profile writes, or product code changes. */
const icons={
 resume:'<path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"/><path d="M14 3v6h6M8 13h8M8 17h5"/>',
 key:'<circle cx="8" cy="9" r="5"/><path d="m12 13 8 8m-2-2 3-3m-6 0 3-3"/>',
 tracker:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 10h18M9 10v10M15 10v10"/>',
 settings:'<path d="m9 3-1 3-3 1-2 3 2 2-1 3 2 3 3-1 3 2 3-2 3 1 2-3-1-3 2-2-2-3-3-1-1-3z"/><circle cx="12" cy="12" r="3"/>',
 overlay:'<rect x="3" y="4" width="18" height="16" rx="2"/><rect x="12" y="11" width="9" height="9" rx="1"/>',
 lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4M12 14v3"/>',
 grip:'<circle cx="9" cy="5" r=".7"/><circle cx="15" cy="5" r=".7"/><circle cx="9" cy="12" r=".7"/><circle cx="15" cy="12" r=".7"/><circle cx="9" cy="19" r=".7"/><circle cx="15" cy="19" r=".7"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',
 trash:'<path d="M4 7h16M9 7V4h6v3M6 7l1 13h10l1-13M10 11v5M14 11v5"/>',
 edit:'<path d="m16 3 5 5-13 13H3v-5zM13 6l5 5"/>',
 check:'<path d="m5 12 4 4 10-10"/>',
 chevron:'<path d="m6 9 6 6 6-6"/>',
 down:'<path d="M12 4v16m-6-6 6 6 6-6"/>',
 up:'<path d="M12 20V4m-6 6 6-6 6 6"/>',
 undo:'<path d="m8 4-5 5 5 5M3 9h10a7 7 0 0 1 7 7v3"/>',
 redo:'<path d="m16 4 5 5-5 5M21 9H11a7 7 0 0 0-7 7v3"/>',
 more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',
 link:'<path d="m10 13 4-4M8 15l-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 3 1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0"/>',
 warning:'<path d="m12 3 10 18H2zM12 9v5M12 17v.1"/>',
 info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7v.1"/>',
 download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',
 eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',
 close:'<path d="m6 6 12 12M6 18 18 6"/>',
 browser:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M7 6.5h.1M10 6.5h.1"/>',
 arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
 shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6z"/><path d="m8 12 3 3 5-6"/>',
 copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>'
};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.resume}</svg>`;
const btn=(label,cls='',name='')=>`<button class="btn ${cls}" type="button">${name?icon(name):''}${label}</button>`;
const iconBtn=(name,label,cls='')=>`<button class="btn square ${cls}" type="button" aria-label="${label}" title="${label}">${icon(name)}</button>`;
const field=(label,value,type='text')=>`<label class="field">${label}<input type="${type}" value="${value}" ${type==='password'?'autocomplete="off"':''}/></label>`;
const select=(label,options,cls='')=>`<label class="field ${cls}"><span>${label}</span><select>${options.map(v=>`<option>${v}</option>`).join('')}</select></label>`;
const pill=(label,cls='')=>`<span class="pill ${cls}"><span class="dot"></span>${label}</span>`;
const query=new URLSearchParams(location.search);
let screen=query.get('screen')||'gallery';
const modes=(active)=>`<div class="segmented" aria-label="Master resume mode"><a href="?screen=edit" class="${active==='edit'?'active':''}">Edit</a><a href="?screen=view" class="${active==='view'?'active':''}">View</a><button type="button" title="Import remains in the existing app">Import</button></div>`;
const aiTabs=active=>`<nav class="tabs" aria-label="AI section"><a href="?screen=keys" class="${active==='keys'?'active':''}">My Keys</a><a href="?screen=data" class="${active==='data'?'active':''}">Data</a></nav>`;
function shell(content,destination,title,description='',headRight=''){
 const items=[['edit','Master resume','resume'],['keys','AI & monitoring','key'],['tracker','Application tracker','tracker'],['settings','Settings','settings']];
 return `<div class="app-shell"><div class="native-bar"><div class="window-dots"><span></span><span></span><span></span></div>Open Resume Toolkit<span class="concept-label">UI concept • illustrative data</span></div><div class="app-grid"><aside class="rail"><div class="rail-title">Your workspace<small>Open Resume Toolkit</small></div><nav aria-label="Workspace areas">${items.map(([id,label,i])=>`<a class="rail-link ${destination===id?'active':''}" href="?screen=${id==='tracker'?'edit':id}" ${destination===id?'aria-current="page"':''}>${icon(i)}${label}</a>`).join('')}</nav><div class="rail-bottom"><a class="rail-overlay" href="?screen=overlay">${icon('overlay')}Show overlay</a><div class="rail-state">${icon('lock')}<span>Encrypted storage<br/>Ready on this device</span></div></div></aside><main class="main"><header class="page-head"><div><h1>${title}</h1>${description?`<p class="subtext">${description}</p>`:''}</div>${headRight||`<div class="head-state">${pill('Local workspace')}</div>`}</header>${content}</main></div></div>`;
}
function resumeBody(edit=false){
 const entry=(title,company,date,bullets,editing=false)=>`<article class="resume-entry"><div class="resume-entry-head"><strong class="${edit?'editable':''}" ${edit?'title="Edit title"':''}>${title}</strong><span class="${edit?'editable':''}">${date}</span></div><div class="${edit?'editable':''}">${company}</div>${edit?`<div class="row small" style="font-family:Hanken,sans-serif;color:#607A7F;gap:16px;margin-top:5px"><button class="btn quiet compact" style="height:22px;padding:0;font-size:10px">Add skills / details</button><button class="btn quiet compact" style="height:22px;padding:0;font-size:10px">Add location</button><button class="btn quiet compact" style="height:22px;padding:0;font-size:10px">Add extra</button></div>`:''}${editing?`<div class="editing-block"><div class="editing-toolbar"><span class="field-caption" style="margin:0 8px 0 0">Information</span><button class="btn" aria-label="Bold"><b>B</b></button><button class="btn" aria-label="Italic"><i>I</i></button><button class="btn text">${icon('link')}Link</button><span class="grow"></span><button class="btn text">Paragraph</button><button class="btn" aria-label="Clear information">${icon('close')}</button></div><textarea aria-label="Experience information">• Led the development of accessible planning tools for cross-functional teams.\n• Reduced report preparation time by 35% with a reusable data validation workflow.\n• Partnered with design and customer teams to simplify onboarding.</textarea></div>`:`<ul>${bullets.map(b=>`<li>${b}</li>`).join('')}</ul>`}${edit?`<div class="item-tools"><span class="grow"></span>${btn('Remove item','quiet compact danger','trash')}</div>`:''}</article>`;
 return `${edit?`<p class="editor-hint">Select any labeled area to edit your resume. Changes save automatically.</p>`:''}<header><div class="${edit?'editable soft':''}"><h2 class="resume-name">Alex Morgan</h2>${edit?icon('edit','edit-glyph'):''}</div><div class="resume-contact ${edit?'editable soft':''}"><span>alex.morgan@example.org &nbsp; • &nbsp; +1 (202) 555-0142 &nbsp; • &nbsp; Portland, OR</span>${edit?icon('edit','edit-glyph'):''}</div>${edit?`<div class="row" style="justify-content:space-between;margin-top:8px;font-family:Hanken,sans-serif">${btn('Add contact information','quiet compact','plus')}<div class="row small muted">Contact divider <select aria-label="Contact divider" style="height:27px;font-size:11px;padding:0 24px 0 8px"><option>Dot</option><option>Bar</option><option>Dash</option></select></div></div>`:''}</header><section class="resume-section"><h3>Experience</h3>${entry('Senior Software Engineer','Example Studio','2022–Present',['Led the development of accessible planning tools for cross-functional teams.','Reduced report preparation time by 35% through a reusable data validation workflow.','Partnered with design and customer teams to simplify onboarding and document editing.'],edit)}${entry('Software Engineer','Northstar Example Cooperative','2019–2022',['Built reliable services in TypeScript and SQL with clear operational documentation.','Introduced automated checks for data quality and keyboard accessibility.'])}${edit?`<button class="add-item">${icon('plus')}Add another item</button>`:''}</section><section class="resume-section"><h3>Projects</h3>${entry('Community Resource Directory','Independent project','2024',['Designed a searchable directory that helps residents find local support services.','Implemented a responsive interface, clear content hierarchy, and accessible navigation.'])}${edit?`<button class="add-item">${icon('plus')}Add another item</button>`:''}</section>${!edit?`<section class="resume-section"><h3>Education</h3>${entry('Example State University','B.S. in Computer Science','2015–2019',['Coursework: software engineering, data structures, human-computer interaction.'])}</section><section class="resume-section"><h3>Skills</h3>${entry('Languages and tools','TypeScript, Rust, Python, SQL, Git, Figma','',['Accessibility, user research, technical writing, and cross-functional collaboration.'])}</section>`:''}`;
}
function edit(){
 const sidebar=`<aside class="section-panel"><div class="section-heading-row">Resume sections</div><p class="small muted">Drag to reorder.<br/>Select a name to rename.</p><div class="section-list"><div class="section-item" style="border-bottom:1px solid var(--line);border-radius:0;margin-bottom:5px">Contact</div>${['Experience','Projects','Education','Skills'].map((s,i)=>`<button class="section-item ${i===0?'active':''}" title="Rename ${s}">${icon('grip')}${s}</button>`).join('')}</div><div class="section-add">${select('Add section',['Custom section','Summary','Experience','Projects','Education','Skills'])}${btn('Add section','','plus')}</div><div class="trash-drop">${icon('trash')}<span>Drag a section here<br/>to delete</span></div></aside>`;
 return shell(`<div class="toolbar">${modes('edit')}<span class="toolbar-spacer"></span>${select('Resume style',['Technical / Engineering','Professional','Modern'])}${btn('Publish','primary')}</div><div class="work-area">${sidebar}<section class="document-area"><div class="doc-status"><span class="row">Your resume ${pill('Saved locally')}</span><div class="history">${iconBtn('undo','Undo edit','compact')}${iconBtn('redo','Redo edit','compact')}</div></div><article class="paper edit-paper">${resumeBody(true)}</article></section></div>`,'edit','Master resume','',`<div class="head-state"><span class="muted">Tailoring uses your published resume</span>${pill('Draft saved')}</div>`);
}
function view(){return shell(`<div class="toolbar">${modes('view')}<span class="toolbar-spacer"></span>${select('Resume style',['Technical / Engineering','Professional','Modern'])}${btn('Publish','primary')}</div><section class="view-stage"><div class="view-meta"><div class="segmented" aria-label="Resume version"><button class="active" data-version="saved">Saved resume</button><button data-version="published">Published resume</button></div><div class="row"><span class="small muted">Export shown version</span>${btn('Export PDF','primary','download')}${btn('Export Word','','download')}</div></div><article class="paper view-paper">${resumeBody(false)}</article><p class="view-footer" id="version-note">Saved resume shown. Tailoring uses the published resume.</p></section>`,'edit','Master resume','',`<div class="head-state">${pill('Draft saved')}<span class="muted">Published version available</span></div>`)}
function budget(value,limit,pct){return `<div><div class="budget-top"><span><strong>${value}</strong> <span class="muted">/</span> <button aria-label="Edit spending limit">${limit}</button></span><span class="muted">${pct}%</span></div><div class="progress" role="img" aria-label="${pct} percent of spending cap used"><div style="width:${pct}%"></div></div><div class="budget-actions"><button>Restart cap</button><button>Remove limit</button></div></div>`}
function keyRow(name,provider,spend,capValue,limit,pct,state){return `<div class="key-row ${state==='active'?'active-key':''} ${state==='paused'?'paused':''}" tabindex="0" aria-label="${name}, ${provider}. Drag or press Enter to move this key."><div><div class="key-identity"><span class="drag-grip">${icon('grip')}</span><div><div class="row" style="gap:8px"><span class="key-name">${name}</span>${state==='paused'?pill('Paused','neutral'):''}</div><p class="key-provider">${provider}</p></div></div><div class="key-model"><select aria-label="Model preset for ${name}" ${state==='paused'?'disabled':''}><option>Balanced: Sample ${provider} model</option><option>Economy: Sample model</option><option>Quality: Sample model</option></select></div></div>${budget(capValue,limit,pct)}<div class="spend"><strong>${spend}</strong><span>Lifetime estimate</span></div>${iconBtn('more',`Test, pause, or remove ${name}`)}</div>`}
function keys(){return shell(`${aiTabs('keys')}<div class="content"><section class="panel"><div class="panel-heading"><div><h2>API keys</h2><p>Keys stay in your operating-system vault.</p></div>${btn('Add key','primary','plus')}</div><div class="key-section-label"><span>Active key</span><span class="small muted">1 of 1</span></div>${keyRow('OpenAI key','OpenAI','$0.456780','$0.456780','$10.00',4,'active')}<div class="key-section-label"><span>All keys</span><span class="small muted">2 stored keys</span></div>${keyRow('Anthropic key','Anthropic','$0.914338','$0.720000','$5.00',14,'available')}${keyRow('Gemini key','Gemini','$0.915924','$0.915924','Unlimited',0,'paused')}<p class="key-guidance">${icon('info')}Drag an unpaused key into Active key to use it. Press Enter to move a focused key.</p></section><section class="panel general-spending"><div><h2>General spending</h2><p class="subtext">One limit shared across all API keys.</p></div><div class="spend"><strong>$2.287042</strong><span>Lifetime estimate across all keys</span></div>${budget('$2.287042','$20.00',11)}</section><p class="estimate-note">${icon('info')}Estimates cover this installation only. Your provider’s billing dashboard is the source of truth.</p></div>`,'keys','AI & monitoring','Choose your active key and manage local spending limits.')}
function chart(){
 const raw=[0,.0082,.0087,.0094,.0101,.0109,0,.0088,.01,.0107,.0114,.0123,0,.0154,.0125,.0134,.0142,.015,0,.016,.0164,.0128,.0132,.0134,0,.0135,.0135,.0135,.0095,.0096];
 const factor=.303380/raw.reduce((sum,v)=>sum+v,0);
 const priced=raw.map(v=>v*factor);
 const points=priced.map((v,i)=>`${68+i*30.7},${190-v/.02*155}`).join(' ');
 return `<svg class="chart-svg" viewBox="0 0 1020 238" role="img" aria-label="Illustrative daily recorded USD estimates for September 5 to October 4. Month estimate 0.303380 USD; 25 operations and 50 attempts. One attempt has unknown usage.">${[0,.005,.01,.015,.02].map((v,i)=>`<line x1="68" y1="${190-i*38.75}" x2="970" y2="${190-i*38.75}" stroke="#DCE6E8"/><text x="54" y="${194-i*38.75}" text-anchor="end">${v.toFixed(3)}</text>`).join('')}<polygon points="68,190 ${points} 958.3,190" fill="#EDF5F6"/><polyline points="${points}" fill="none" stroke="#347F87" stroke-width="2.2" stroke-linejoin="round"/>${priced.map((v,i)=>`<circle cx="${68+i*30.7}" cy="${190-v/.02*155}" r="2.5" fill="#347F87" stroke="white" stroke-width="1"/>`).join('')}${[['Sep 5',68],['Sep 12',283],['Sep 19',498],['Sep 26',713],['Oct 4',958]].map(([t,x])=>`<text x="${x}" y="221" text-anchor="middle">${t}</text>`).join('')}</svg>`;
}
function data(){return shell(`${aiTabs('data')}<div class="content"><section class="panel"><div class="chart-header"><div><h2>All keys</h2><p class="subtext" style="font-size:12px;margin-top:4px">General activity across every provider and model</p></div>${select('Activity view',['All keys','OpenAI key','Anthropic key','Gemini key'])}</div><div class="chart-controls"><div class="row"><div class="segmented"><button class="active">Price</button><button>Tokens</button></div>${select('Currency',['USD'])}</div><div class="segmented"><button>Week</button><button class="active">Month</button><button>Year</button><button>All time</button></div><div class="chart-summary"><strong>$0.303380</strong><div>Recorded estimate · Month<br/>25 operations &nbsp; / &nbsp; 50 attempts</div></div></div>${chart()}<div class="partial-notice">${icon('warning')}<span>1 attempt has partial or unknown usage. Unresolved reservation: $0.120000 maximum,<br/>not confirmed spend. Missing usage is not zero spend.</span></div><p class="estimate-note" style="padding-top:13px;font-size:11px">Estimates cover this installation only. Your provider’s billing dashboard is the source of truth.</p></section><section class="panel data-settings"><h2>Activity settings</h2><p>Manage saved activity independently from the graph.</p><div class="setting-row"><div><strong>Export activity</strong><span>Choose a key and one or more active months.</span></div>${btn('Export JSON…','compact','download')}</div><div class="setting-row"><div><strong>Clear activity</strong><span>Remove selected months without changing spend or caps.</span></div>${btn('Choose activity…','compact')}</div><div class="setting-row"><div><strong>Delete removed key data</strong><span>Delete retained activity for selected removed keys.</span></div>${btn('Choose removed keys…','compact')}</div><div class="setting-row"><div><strong>Activity retention</strong><span>Remove older local activity without resetting caps.</span></div><div class="row">${select('Retention policy',['Retain until cleared','30 days','90 days','One year'])}${btn('Apply retention','compact')}</div></div></section></div>`,'keys','AI & monitoring','Inspect local usage and manage your activity data.')}
function settings(){
 return shell(`<nav class="tabs" aria-label="Settings sections"><a href="?screen=settings" class="active">Backup and recovery</a><a href="?screen=storage">Storage and deletion</a><a href="?screen=browser">Browser connections</a></nav><div class="content settings-content"><div><section class="panel"><h2>Encrypted portable backup</h2><p class="settings-intro">Save an encrypted copy of your resume, published snapshots, settings, render history, and content-free AI activity.</p><div class="backup-fields">${field('Backup passphrase','a long unique passphrase','password')}${field('Confirm passphrase','a long unique passphrase','password')}</div><p class="backup-guidance">Use a long, unique passphrase and store it separately from the backup.<br/>ORT cannot recover this passphrase.</p>${btn('Create encrypted backup','primary','download')}<section class="backup-check"><h3>Check an existing backup</h3><p>Authenticate a backup and review its content-free inventory.<br/>Your current profile is unchanged.</p>${field('Existing backup passphrase','','password')}<div style="margin-top:16px">${btn('Select and check encrypted backup','','shield')}</div></section></section><details class="disclosure"><summary><div><strong>Local recovery safety copy</strong><span>No retained safety copy is present on this device.</span></div>${icon('chevron')}</summary><div class="details-body"><p>A retained safety copy can be restored or deleted with the existing confirmation steps.</p>${field('Type ROLL BACK SAVED PROFILE to confirm','')}${btn('Roll back to retained safety copy')}${field('Type DELETE SAFETY COPY to confirm','')}${btn('Delete retained safety copy','danger')}</div></details><details class="disclosure"><summary><div><strong>Replace saved profile from backup</strong><span>Prepare a verified replacement and activate it after restart.</span></div>${icon('chevron')}</summary><div class="details-body">${field('Existing backup passphrase','','password')}${field('Type REPLACE SAVED PROFILE to confirm','')}${btn('Select backup and prepare replacement','danger')}</div></details></div><aside class="safety-notes">${icon('lock')}<h3>Your backup, under your control</h3><p>The archive is encrypted before it reaches the destination you choose. Existing files are never replaced.</p><div class="rule"></div><h3>What stays on this device</h3><ul><li>${icon('check')}Device encryption keys</li><li>${icon('check')}Provider credentials</li><li>${icon('check')}Active spending-cap authority</li></ul><div class="rule"></div><h3>Restoring a profile</h3><p>A verified replacement activates after restart. The replaced encrypted profile stays on this device as a safety copy.</p><p>External exports and backups remain unchanged.</p></aside></div>`,'settings','Settings','Manage saved data, create a backup, or recover a profile.')
}
function extraSettings(which){
 const nav=`<nav class="tabs"><a href="?screen=settings">Backup and recovery</a><a href="?screen=storage" class="${which==='storage'?'active':''}">Storage and deletion</a><a href="?screen=browser" class="${which==='browser'?'active':''}">Browser connections</a></nav>`;
 const storage=`<section class="panel"><div class="panel-heading"><div><h2>Encrypted profile storage</h2><p>Counts this profile and known journal and manifest files.</p></div>${btn('Refresh usage')}</div><p class="subtext">External exports, backups, OS-vault items, and preview bytes are excluded.</p><div class="setting-row"><strong>Profile database</strong><span>4.2 MB · illustrative value</span></div><div class="setting-row"><strong>Journal and manifest files</strong><span>0.6 MB · illustrative value</span></div><div class="backup-check"><h3>Delete all local ORT data</h3><p>Resume data, retained applications, local activity, and settings will be removed.</p>${field('Type DELETE ALL LOCAL ORT DATA to confirm','')}<div style="margin-top:18px">${btn('Delete all local ORT data','danger')}</div></div></section>`;
 const browser=`<section class="panel"><h2>Chrome development connection</h2><p class="subtext">Development connection enabled.</p><p class="settings-intro">After development host setup, the connection enables on launch. Press Capture on the overlay, then select the top-left and bottom-right corners of the text in Chrome.</p><p class="settings-intro">This connection trusts programs running under your macOS account. Disabling it lasts until the next app launch.</p><div style="margin-top:22px">${btn('Disable development connection')}</div><p class="subtext">Edge support will come later.</p></section>`;
 return shell(`${nav}<div class="content">${which==='storage'?storage:browser}</div>`,'settings','Settings','Manage saved data, create a backup, or recover a profile.');
}
function overlay(){return `<main class="overlay-artboard"><section class="overlay-window" aria-label="Application overlay"><div class="overlay-grab" aria-label="Window drag handle"><span></span></div><header class="overlay-head"><div><label class="field">AI model preset<select><option>Balanced: Sample OpenAI model</option><option>Economy: Sample model</option><option>Quality: Sample model</option></select></label><div class="overlay-status"><span class="dot"></span>Ready</div></div><div class="browser-status">${icon('browser')}Connected</div></header><div class="overlay-body"><h1 class="overlay-company">Example Studio</h1><p class="overlay-role">Senior Software Engineer</p><div class="finish-row">${btn('Finish Application','grow','check')}${iconBtn('edit','Edit tracker details')}${iconBtn('close','End application without saving','danger')}</div><nav class="overlay-tabs" aria-label="Application materials"><a class="active" href="#">Resume</a><a href="#">Cover letter</a><a href="#">Answers</a></nav><section class="tailoring-notes"><h3>Tailoring notes</h3><ul><li>Prioritized documented TypeScript experience.</li><li>Moved the accessible interface project earlier.</li></ul></section><section class="qualification"><h3>${icon('warning')}Qualification gaps</h3><p>Based on your published resume.</p><div class="missing">Missing Kubernetes</div></section>${select('Resume style',['Technical / Engineering','Professional','Modern'])}<section class="overlay-download">${select('Download format',['PDF','Word (.docx)'])}<div class="overlay-action-grid">${btn('Download','primary','download')}${btn('Drag me','drag-button','resume')}${btn('View','','eye')}${btn('Edit','','edit')}</div><p class="overlay-note">${icon('check')}PDF ready to download or drag</p></section><section class="refinement"><label class="field">Refine with AI<textarea placeholder="What would you like to change?"></textarea></label>${btn('Refine resume','primary','arrow')}</section><p class="overlay-foot">Your application edits are saved locally.</p></div></section></main>`}
function logo(){return `<main class="logo-page"><h1>Open Folio</h1><p>A clean, open document mark for Open Resume Toolkit. Two leaves share a spine; the raised right leaf gives the mark its forward direction.</p><div class="logo-lockup"><img src="../logo/open-folio-lockup.svg" alt="Open Resume Toolkit logo"/></div><div class="logo-grid"><div class="logo-tile"><img src="../logo/open-folio-mark.svg" alt="Teal logo mark"/><span>App and web mark</span></div><div class="logo-tile dark"><img src="../logo/open-folio-reversed.svg" alt="White logo mark"/><span>Reversed mark</span></div><div class="logo-tile"><img class="app-icon" src="../logo/open-folio-app.svg" alt="Application icon"/><span>macOS and Windows app icon</span></div></div><footer><span>Vector masters • transparent PNGs • .icns • .ico</span><div class="row">${[16,24,32].map(s=>`<img src="../logo/open-folio-mark.svg" width="${s}" height="${s}" alt="${s} pixel mark"/>`).join('')}<span>Readable at small sizes</span></div></footer></main>`}
function gallery(){const entries=[['edit','Master resume / Edit','A quieter document editor with inline editing and preserved section controls.'],['view','Master resume / View','Saved and published versions with PDF and Word exports.'],['keys','AI & monitoring / My Keys','Active-key selection, model presets, key actions, and spending limits.'],['data','AI & monitoring / Data','Usage filters, estimates, partial usage, export, deletion, and retention.'],['settings','Settings','Backup and recovery, with storage and browser settings preserved.'],['overlay','Captured job / Resume overlay','The tailored resume state after capture and tailoring, with all material controls.'],['logo','Open Folio logo','Independent vector logo and desktop application icon.']];return `<main class="gallery"><h1>A calmer workspace for your next application.</h1><p>UI exploration for Open Resume Toolkit. All examples use synthetic data. The six interface images omit application and provider logos. This package changes no product code.</p><div class="gallery-grid">${entries.map(([id,t,d])=>`<a class="gallery-item" href="?screen=${id}"><img src="../${id==='logo'?'logo/logo-presentation.png':`screens/${id}.png`}" alt="${t}"/><strong>${t}</strong><span>${d}</span></a>`).join('')}</div><footer>Hanken Grotesk interface typography · independent professional document typography · muted blue-green palette</footer></main>`}
const renderers={edit,view,keys,data,settings,overlay,logo,gallery,storage:()=>extraSettings('storage'),browser:()=>extraSettings('browser')};
document.getElementById('app').innerHTML=(renderers[screen]||gallery)();
document.querySelectorAll('[data-version]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-version]').forEach(v=>v.classList.toggle('active',v===b));document.getElementById('version-note').textContent=b.dataset.version==='published'?'Published resume shown. This is the version used for tailoring.':'Saved resume shown. Tailoring uses the published resume.';}));
