[package]
name = "ort-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ort-domain = { path = "../ort-domain" }
cap-std.workspace = true
cap-primitives.workspace = true
uuid.workspace = true
thiserror.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
ort-documents = { path = "../ort-documents" }
sha2.workspace = true
security-framework = "=3.7.0"
rustix = { version = "=1.1.4", features = ["event", "fs"] }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
