//! Fixed-template, memory-only PDF output. No user source, paths or font discovery.
use std::sync::{LazyLock, Mutex};

use ort_domain::{
    DocumentStyle, Link, MAX_PDF_BYTES, MAX_PDF_PAGES, PdfRenderReceipt, ResumeDocument,
};
use serde::Serialize;
use sha2::{Digest, Sha256};
use typst::{
    Library, LibraryExt, World,
    diag::{FileError, FileResult},
    foundations::{Bytes, Datetime, Dict, Duration, Smart, Value},
    layout::{Frame, FrameItem, Point, Transform},
    syntax::{FileId, Source},
    text::{Font, FontBook},
    utils::LazyHash,
};

pub const RENDERER_VERSION: &str = "typst-0.15.1/ort-1";
pub const TEMPLATE_ID: &str = "plain_pdf_v1";
pub const FONT_BUNDLE_ID: &str = "libertinus-serif/typst-assets-0.15.1";
const TEMPLATE: &str = include_str!("../../../templates/resume/plain_pdf_v1.typ");
const MAX_LAYOUT_BLOCKS: usize = 800;
const MAX_HARD_BREAKS: usize = 200;
const PARAGRAPH_FIELD_LABEL: &str = "__ort_body_paragraph__";
static RENDER_LOCK: Mutex<()> = Mutex::new(());
static SOURCE: LazyLock<Source> = LazyLock::new(|| Source::detached(TEMPLATE));
static TECHNICAL_SOURCE: LazyLock<Source> =
    LazyLock::new(|| Source::detached(template(DocumentStyle::Technical)));
static PROFESSIONAL_SOURCE: LazyLock<Source> =
    LazyLock::new(|| Source::detached(template(DocumentStyle::Professional)));
static MODERN_SOURCE: LazyLock<Source> =
    LazyLock::new(|| Source::detached(template(DocumentStyle::Modern)));

fn template(style: DocumentStyle) -> &'static str {
    match style {
        DocumentStyle::Plain => TEMPLATE,
        DocumentStyle::Technical => include_str!("../../../templates/resume/technical_pdf_v1.typ"),
        DocumentStyle::Professional => {
            include_str!("../../../templates/resume/professional_pdf_v1.typ")
        }
        DocumentStyle::Modern => include_str!("../../../templates/resume/modern_pdf_v1.typ"),
    }
}

const MODERN_FONT_BUNDLE_ID: &str = "liberation-sans/pdfjs-6.3.289";
const MODERN_FONT_BYTES: [&[u8]; 4] = [
    include_bytes!("../fonts/LiberationSans-Regular.ttf"),
    include_bytes!("../fonts/LiberationSans-Bold.ttf"),
    include_bytes!("../fonts/LiberationSans-Italic.ttf"),
    include_bytes!("../fonts/LiberationSans-BoldItalic.ttf"),
];
// Fixed, compiled-in faces only: the original six serif faces followed by
// four sans-serif faces used by Modern. Historical serif indices stay fixed.
static FONTS: LazyLock<Vec<Font>> = LazyLock::new(|| {
    typst_assets::fonts()
        .take(6)
        .chain(MODERN_FONT_BYTES)
        .map(|bytes| Font::new(Bytes::new(bytes), 0).expect("reviewed bundled font"))
        .collect()
});
static BOOK: LazyLock<LazyHash<FontBook>> =
    LazyLock::new(|| LazyHash::new(FontBook::from_fonts(FONTS.iter())));

#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum PdfRenderError {
    #[error("the saved document cannot be rendered")]
    InvalidContent,
    #[error("the bundled fonts do not support this content")]
    UnsupportedGlyph,
    #[error("the document exceeds the PDF layout limit")]
    LayoutLimit,
    #[error("the document exceeds the PDF byte limit")]
    OutputTooLarge,
    #[error("the PDF renderer is unavailable")]
    Unavailable,
}

// No Debug: generated bytes and text must not enter diagnostics.
pub struct PdfArtifact {
    pub bytes: Vec<u8>,
    pub receipt: PdfRenderReceipt,
}

#[derive(Serialize)]
struct InlineRun {
    text: String,
    bold: bool,
    italic: bool,
    url: Option<String>,
}

#[derive(Serialize)]
struct Paragraph {
    kind: &'static str,
    text: String,
    right: Option<String>,
    runs: Vec<InlineRun>,
    right_runs: Vec<InlineRun>,
    sticky: bool,
    entry_end: bool,
    body_start: bool,
}

fn normalized(value: &str) -> String {
    value
        .replace("\r\n", "\n")
        .replace('\r', "\n")
        .trim()
        .to_owned()
}

fn inline_runs(value: &str, force_bold: bool, force_italic: bool) -> Vec<InlineRun> {
    ort_documents::parse_inline_text(&normalized(value))
        .into_iter()
        .map(|span| InlineRun {
            text: span.text,
            bold: force_bold || span.bold,
            italic: force_italic || span.italic,
            url: span.url,
        })
        .collect()
}

fn plain_runs(runs: &[InlineRun]) -> String {
    runs.iter().map(|run| run.text.as_str()).collect()
}

fn push_paragraph(
    paragraphs: &mut Vec<Paragraph>,
    kind: &'static str,
    runs: Vec<InlineRun>,
    right_runs: Vec<InlineRun>,
) {
    let text = plain_runs(&runs);
    let right = plain_runs(&right_runs);
    if text.is_empty() && right.is_empty() {
        return;
    }
    paragraphs.push(Paragraph {
        kind,
        text,
        right: (!right.is_empty()).then_some(right),
        runs,
        right_runs,
        sticky: false,
        entry_end: false,
        body_start: false,
    });
}

fn add(paragraphs: &mut Vec<Paragraph>, kind: &'static str, value: &str) {
    push_paragraph(paragraphs, kind, inline_runs(value, false, false), vec![]);
}

fn link(paragraphs: &mut Vec<Paragraph>, value: &Link) -> Result<(), PdfRenderError> {
    if value.url.chars().any(char::is_whitespace) {
        return Err(PdfRenderError::InvalidContent);
    }
    let label = normalized(&value.label);
    let url = normalized(&value.url);
    let text = if label.is_empty() { url.clone() } else { label };
    push_paragraph(
        paragraphs,
        "link",
        vec![InlineRun {
            text,
            bold: false,
            italic: false,
            url: Some(url),
        }],
        vec![],
    );
    Ok(())
}

fn append_runs(target: &mut Vec<InlineRun>, value: &str, bold: bool, italic: bool) {
    target.extend(inline_runs(value, bold, italic));
}

fn append_separator(target: &mut Vec<InlineRun>, separator: &str) {
    if !target.is_empty() {
        target.push(InlineRun {
            text: separator.to_owned(),
            bold: false,
            italic: false,
            url: None,
        });
    }
}

fn append_link(target: &mut Vec<InlineRun>, value: &Link) -> Result<(), PdfRenderError> {
    if value.url.chars().any(char::is_whitespace) {
        return Err(PdfRenderError::InvalidContent);
    }
    let url = normalized(&value.url);
    let label = normalized(&value.label);
    target.push(InlineRun {
        text: if label.is_empty() { url.clone() } else { label },
        bold: false,
        italic: false,
        url: Some(url),
    });
    Ok(())
}

fn paragraphs(
    document: &ResumeDocument,
    style: DocumentStyle,
) -> Result<Vec<Paragraph>, PdfRenderError> {
    ort_documents::render_plain_text(document).map_err(|_| PdfRenderError::InvalidContent)?;
    let mut out = Vec::new();
    push_paragraph(
        &mut out,
        "name",
        inline_runs(
            &document.contact.full_name,
            style != DocumentStyle::Professional,
            false,
        ),
        vec![],
    );
    if style == DocumentStyle::Plain {
        for value in [
            &document.contact.email,
            &document.contact.phone,
            &document.contact.location,
        ] {
            add(&mut out, "text", value);
        }
    } else {
        let mut contact = Vec::new();
        for value in [
            &document.contact.email,
            &document.contact.phone,
            &document.contact.location,
        ] {
            if !normalized(value).is_empty() {
                append_separator(&mut contact, "  •  ");
                append_runs(&mut contact, value, false, false);
            }
        }
        for value in &document.contact.links {
            append_separator(&mut contact, "  •  ");
            append_link(&mut contact, value)?;
        }
        push_paragraph(&mut out, "contact", contact, vec![]);
    }
    if style == DocumentStyle::Plain {
        for value in &document.contact.links {
            link(&mut out, value)?;
        }
    }
    for section in &document.sections {
        let mut entries = Vec::new();
        for entry in &section.entries {
            let entry_start = entries.len();
            entry_header(&mut entries, entry);
            let body_start = entries.len();
            if let Some(body) = entry
                .fields
                .iter()
                .find(|field| field.label == PARAGRAPH_FIELD_LABEL)
                .map(|field| field.value.as_str())
                .filter(|value| !value.trim().is_empty())
            {
                add(&mut entries, "text", body);
            } else {
                for bullet in &entry.bullets {
                    add(&mut entries, "bullet", &bullet.text);
                }
            }
            for value in &entry.links {
                link(&mut entries, value)?;
            }
            let entry_end = entries.len();
            if entry_end > entry_start {
                entries[entry_end - 1].entry_end = true;
                if body_start > entry_start && body_start < entry_end {
                    entries[body_start].body_start = true;
                }
            }
            // Keep ordinary entries intact at page boundaries. Exceptionally
            // large entries remain breakable so they can span pages safely.
            if entry_end > entry_start && entry_end - entry_start <= 10 {
                for paragraph in &mut entries[entry_start..entry_end - 1] {
                    paragraph.sticky = true;
                }
            }
        }
        if !entries.is_empty() {
            push_paragraph(
                &mut out,
                "section",
                inline_runs(&section.heading, true, false),
                vec![],
            );
            out.extend(entries);
        }
    }
    validate_paragraphs(&out, style)?;
    Ok(out)
}

fn validate_paragraphs(out: &[Paragraph], style: DocumentStyle) -> Result<(), PdfRenderError> {
    if out.len() > MAX_LAYOUT_BLOCKS
        || out
            .iter()
            .map(|p| {
                p.text.matches('\n').count()
                    + p.right.as_deref().unwrap_or("").matches('\n').count()
            })
            .sum::<usize>()
            > MAX_HARD_BREAKS
    {
        return Err(PdfRenderError::LayoutLimit);
    }
    // Do not silently substitute missing characters. Check all selected faces:
    // headings and ordinary text must both have coverage. No system fallback.
    for c in out
        .iter()
        .flat_map(|p| {
            p.text
                .chars()
                .chain(p.right.as_deref().unwrap_or("").chars())
        })
        .filter(|c| !c.is_whitespace())
    {
        if (if style == DocumentStyle::Modern {
            &FONTS[6..]
        } else {
            &FONTS[..6]
        })
        .iter()
        .any(|font| !font.info().coverage.contains(u32::from(c)))
        {
            return Err(PdfRenderError::UnsupportedGlyph);
        }
    }
    Ok(())
}

fn entry_header(entries: &mut Vec<Paragraph>, entry: &ort_domain::ResumeEntry) {
    let mut title = inline_runs(&entry.heading, true, false);
    if let Some(details) = entry.fields.iter().find(|field| {
        field.label != PARAGRAPH_FIELD_LABEL
            && !field.label.trim().eq_ignore_ascii_case("extra")
            && !field.value.trim().is_empty()
    }) {
        append_separator(&mut title, " | ");
        append_runs(&mut title, &details.value, false, false);
    }
    let dates = if entry.date_range.trim().is_empty() {
        entry
            .dates
            .iter()
            .flatten()
            .map(ort_domain::ResumeDate::display_text)
            .collect::<Vec<_>>()
            .join("\n")
    } else {
        entry.date_range.clone()
    };
    let extras = entry
        .fields
        .iter()
        .filter(|field| {
            field.label.trim().eq_ignore_ascii_case("extra") && !field.value.trim().is_empty()
        })
        .map(|field| field.value.as_str())
        .collect::<Vec<_>>()
        .join("\n");
    let mut right_rows = [entry.location.as_str(), dates.as_str(), extras.as_str()]
        .into_iter()
        .map(|value| inline_runs(value, false, false))
        .filter(|runs| !runs.is_empty());

    push_paragraph(
        entries,
        "entry",
        title,
        right_rows.next().unwrap_or_default(),
    );
    push_paragraph(
        entries,
        "subrow",
        inline_runs(&entry.subheading, false, false),
        right_rows.next().unwrap_or_default(),
    );
    for right in right_rows {
        push_paragraph(entries, "meta", vec![], right);
    }
}

struct MemoryWorld {
    library: LazyHash<Library>,
    source: Source,
}

impl MemoryWorld {
    fn new(paragraphs: &[Paragraph], style: DocumentStyle) -> Result<Self, PdfRenderError> {
        let json = serde_json::to_string(paragraphs).map_err(|_| PdfRenderError::InvalidContent)?;
        let mut inputs = Dict::new();
        inputs.insert("resume".into(), Value::Str(json.into()));
        Ok(Self {
            library: LazyHash::new(Library::builder().with_inputs(inputs).build()),
            source: match style {
                DocumentStyle::Plain => SOURCE.clone(),
                DocumentStyle::Technical => TECHNICAL_SOURCE.clone(),
                DocumentStyle::Professional => PROFESSIONAL_SOURCE.clone(),
                DocumentStyle::Modern => MODERN_SOURCE.clone(),
            },
        })
    }
}

impl World for MemoryWorld {
    fn library(&self) -> &LazyHash<Library> {
        &self.library
    }
    fn book(&self) -> &LazyHash<FontBook> {
        &BOOK
    }
    fn main(&self) -> FileId {
        self.source.id()
    }
    fn source(&self, id: FileId) -> FileResult<Source> {
        if id == self.source.id() {
            Ok(self.source.clone())
        } else {
            Err(FileError::AccessDenied)
        }
    }
    fn file(&self, id: FileId) -> FileResult<Bytes> {
        if id == self.source.id() {
            Ok(Bytes::from_string(self.source.text().to_owned()))
        } else {
            Err(FileError::AccessDenied)
        }
    }
    fn font(&self, index: usize) -> Option<Font> {
        FONTS.get(index).cloned()
    }
    fn today(&self, _offset: Option<Duration>) -> Option<Datetime> {
        None
    }
}

struct EvictMemoizedContent;
impl Drop for EvictMemoizedContent {
    fn drop(&mut self) {
        comemo::evict(0);
    }
}

#[must_use]
pub fn sha256(bytes: &[u8]) -> String {
    hex::encode(Sha256::digest(bytes))
}

// The reviewed template has only translated groups, text, links and tags.
// Reject overflow after layout (including very long unbreakable words), missing
// shaped glyphs, clipping, images or newly introduced drawing/transform behavior.
fn visible_frame(frame: &Frame, origin: Point, depth: usize) -> bool {
    if depth > 64 {
        return false;
    }
    frame.items().all(|(position, item)| {
        let point = origin + *position;
        match item {
            FrameItem::Group(group) => {
                group.clip.is_none()
                    && group.transform == Transform::identity()
                    && visible_frame(&group.frame, point, depth + 1)
            }
            FrameItem::Text(text) => {
                if text.glyphs.iter().any(|glyph| glyph.id == 0) {
                    return false;
                }
                if text.text.chars().all(char::is_whitespace) {
                    return true;
                }
                let bounds = text.bbox();
                [point + bounds.min, point + bounds.max]
                    .iter()
                    .all(|point| {
                        (32.0..=580.0).contains(&point.x.to_pt())
                            && (28.0..=764.0).contains(&point.y.to_pt())
                    })
            }
            FrameItem::Link(..) | FrameItem::Tag(..) => true,
            FrameItem::Shape(shape, _) => {
                // Only thin, horizontal section rules from bundled templates.
                // Images, fills, curves, clipping and transformed drawing stay denied.
                if let typst::visualize::Geometry::Line(end) = &shape.geometry {
                    shape.fill.is_none()
                        && shape.stroke.as_ref().is_some_and(|stroke| {
                            stroke.thickness.to_pt() > 0.0 && stroke.thickness.to_pt() <= 1.5
                        })
                        && end.y.to_pt() == 0.0
                        && end.x.to_pt() >= 0.0
                        && [point, point + *end].iter().all(|p| {
                            (33.0..=579.0).contains(&p.x.to_pt())
                                && (29.0..=763.0).contains(&p.y.to_pt())
                        })
                } else {
                    false
                }
            }
            FrameItem::Image(..) => false,
        }
    })
}

/// # Errors
/// Refuses invalid content, uncovered glyphs, layout/output limits, and compiler
/// warnings. Error messages never contain template diagnostics or resume text.
pub fn render_pdf(document: &ResumeDocument) -> Result<PdfArtifact, PdfRenderError> {
    render_pdf_with_style(document, DocumentStyle::Plain)
}

/// Renders only a reviewed, compiled-in template. Historical plain output stays
/// byte-identical; receipts identify the selected template and its exact source.
///
/// # Errors
/// Applies the same content, font, geometry, page and byte bounds to every style.
pub fn render_pdf_with_style(
    document: &ResumeDocument,
    style: DocumentStyle,
) -> Result<PdfArtifact, PdfRenderError> {
    let _guard = RENDER_LOCK
        .lock()
        .map_err(|_| PdfRenderError::Unavailable)?;
    let _eviction = EvictMemoizedContent;
    let content = paragraphs(document, style)?;
    let world = MemoryWorld::new(&content, style)?;
    let compiled = typst::compile::<typst_layout::PagedDocument>(&world);
    if !compiled.warnings.is_empty() {
        return Err(PdfRenderError::InvalidContent);
    }
    let output = compiled
        .output
        .map_err(|_| PdfRenderError::InvalidContent)?;
    if output.pages().is_empty() || output.pages().len() > MAX_PDF_PAGES {
        return Err(PdfRenderError::LayoutLimit);
    }
    if !output
        .pages()
        .iter()
        .all(|page| visible_frame(&page.frame, Point::zero(), 0))
    {
        return Err(PdfRenderError::LayoutLimit);
    }
    let bytes = typst_pdf::pdf(
        &output,
        &typst_pdf::PdfOptions {
            creator: Smart::Custom(None),
            ..Default::default()
        },
    )
    .map_err(|_| PdfRenderError::InvalidContent)?;
    if bytes.is_empty() || bytes.len() > MAX_PDF_BYTES {
        return Err(PdfRenderError::OutputTooLarge);
    }
    let mut font_hash = Sha256::new();
    if style == DocumentStyle::Modern {
        for font in MODERN_FONT_BYTES {
            font_hash.update(font);
        }
    } else {
        for font in typst_assets::fonts().take(6) {
            font_hash.update(font);
        }
    }
    let receipt = PdfRenderReceipt {
        document_sha256: sha256(
            &serde_json::to_vec(document).map_err(|_| PdfRenderError::InvalidContent)?,
        ),
        document_schema_version: document.schema_version,
        pdf_sha256: sha256(&bytes),
        renderer_version: RENDERER_VERSION.into(),
        template_id: style.pdf_template_id().into(),
        template_sha256: sha256(template(style).as_bytes()),
        font_bundle_id: if style == DocumentStyle::Modern {
            MODERN_FONT_BUNDLE_ID
        } else {
            FONT_BUNDLE_ID
        }
        .into(),
        font_bundle_sha256: hex::encode(font_hash.finalize()),
        page_count: output.pages().len(),
        byte_count: bytes.len(),
    };
    Ok(PdfArtifact { bytes, receipt })
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn bundled_template_compiles_without_warnings() {
        let _guard = RENDER_LOCK.lock().unwrap();
        for style in [
            DocumentStyle::Plain,
            DocumentStyle::Technical,
            DocumentStyle::Professional,
            DocumentStyle::Modern,
        ] {
            let world = MemoryWorld::new(
                &[
                    Paragraph {
                        kind: "name",
                        text: "Synthetic".into(),
                        right: None,
                        runs: vec![InlineRun {
                            text: "Synthetic".into(),
                            bold: true,
                            italic: false,
                            url: None,
                        }],
                        right_runs: vec![],
                        sticky: false,
                        entry_end: false,
                        body_start: false,
                    },
                    Paragraph {
                        kind: "entry",
                        text: "Software Engineer".into(),
                        right: Some("2023-2026".into()),
                        runs: vec![InlineRun {
                            text: "Software Engineer".into(),
                            bold: true,
                            italic: false,
                            url: None,
                        }],
                        right_runs: vec![InlineRun {
                            text: "2023-2026".into(),
                            bold: false,
                            italic: false,
                            url: None,
                        }],
                        sticky: false,
                        entry_end: false,
                        body_start: false,
                    },
                ],
                style,
            )
            .unwrap();
            let result = typst::compile::<typst_layout::PagedDocument>(&world);
            assert!(
                result.warnings.is_empty(),
                "{style:?}: {:?}",
                result.warnings
            );
            assert!(
                result.output.is_ok(),
                "{style:?}: {:?}",
                result.output.err()
            );
            let output = result.output.unwrap();
            assert!(
                output
                    .pages()
                    .iter()
                    .all(|page| visible_frame(&page.frame, Point::zero(), 0)),
                "{style:?}: frame rejected"
            );
        }
    }

    #[test]
    fn world_denies_external_files_packages_plugins_and_font_discovery() {
        let _guard = RENDER_LOCK.lock().unwrap();
        let mut world = MemoryWorld::new(&[], DocumentStyle::Plain).unwrap();
        let other = typst::syntax::RootedPath::new(
            typst::syntax::VirtualRoot::Project,
            typst::syntax::VirtualPath::new("unavailable").unwrap(),
        )
        .intern();
        assert!(matches!(world.source(other), Err(FileError::AccessDenied)));
        assert!(matches!(world.file(other), Err(FileError::AccessDenied)));
        assert_eq!(FONTS.len(), 10);
        assert!(
            FONTS[..6]
                .iter()
                .all(|font| font.info().family == "Libertinus Serif")
        );
        assert!(
            FONTS[6..]
                .iter()
                .all(|font| font.info().family == "Liberation Sans")
        );
        assert!(world.font(10).is_none());
        assert!(world.today(None).is_none());
        for code in [
            r#"#read("/private/secret")"#,
            r#"#include "private.typ""#,
            r#"#import "@preview/unavailable:1.0.0": *"#,
            r#"#image("private.png")"#,
            r#"#plugin("private.wasm")"#,
        ] {
            world.source = Source::detached(code);
            assert!(
                typst::compile::<typst_layout::PagedDocument>(&world)
                    .output
                    .is_err()
            );
        }
    }
}
