//! Fixed-template, memory-only PDF output. No user source, paths or font discovery.
use std::sync::{LazyLock, Mutex};

use ort_domain::{Link, MAX_PDF_BYTES, MAX_PDF_PAGES, PdfRenderReceipt, ResumeDocument};
use serde::Serialize;
use sha2::{Digest, Sha256};
use typst::{
    Library, LibraryExt, World,
    diag::{FileError, FileResult},
    foundations::{Bytes, Datetime, Dict, Duration, Smart, Value},
    layout::{Frame, FrameItem, Point, Transform},
    syntax::{FileId, Source},
    text::{Font, FontBook},
    utils::LazyHash,
};

pub const RENDERER_VERSION: &str = "typst-0.15.1/ort-1";
pub const TEMPLATE_ID: &str = "plain_pdf_v1";
pub const FONT_BUNDLE_ID: &str = "libertinus-serif/typst-assets-0.15.1";
const TEMPLATE: &str = include_str!("../../../templates/resume/plain_pdf_v1.typ");
const MAX_LAYOUT_BLOCKS: usize = 800;
const MAX_HARD_BREAKS: usize = 200;
static RENDER_LOCK: Mutex<()> = Mutex::new(());
static SOURCE: LazyLock<Source> = LazyLock::new(|| Source::detached(TEMPLATE));

// Only the six Libertinus Serif faces, in the pinned asset package's fixed order.
static FONTS: LazyLock<Vec<Font>> = LazyLock::new(|| {
    typst_assets::fonts()
        .take(6)
        .map(|bytes| Font::new(Bytes::new(bytes), 0).expect("reviewed bundled font"))
        .collect()
});
static BOOK: LazyLock<LazyHash<FontBook>> =
    LazyLock::new(|| LazyHash::new(FontBook::from_fonts(FONTS.iter())));

#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum PdfRenderError {
    #[error("the saved document cannot be rendered")]
    InvalidContent,
    #[error("the bundled fonts do not support this content")]
    UnsupportedGlyph,
    #[error("the document exceeds the PDF layout limit")]
    LayoutLimit,
    #[error("the document exceeds the PDF byte limit")]
    OutputTooLarge,
    #[error("the PDF renderer is unavailable")]
    Unavailable,
}

// No Debug: generated bytes and text must not enter diagnostics.
pub struct PdfArtifact {
    pub bytes: Vec<u8>,
    pub receipt: PdfRenderReceipt,
}

#[derive(Serialize)]
struct Paragraph {
    kind: &'static str,
    text: String,
    url: Option<String>,
}

fn normalized(value: &str) -> String {
    value
        .replace("\r\n", "\n")
        .replace('\r', "\n")
        .trim()
        .to_owned()
}

fn add(paragraphs: &mut Vec<Paragraph>, kind: &'static str, value: &str) {
    let text = normalized(value);
    if !text.is_empty() {
        paragraphs.push(Paragraph {
            kind,
            text,
            url: None,
        });
    }
}

fn link(paragraphs: &mut Vec<Paragraph>, value: &Link) -> Result<(), PdfRenderError> {
    if value.url.chars().any(char::is_whitespace) {
        return Err(PdfRenderError::InvalidContent);
    }
    let label = normalized(&value.label);
    let url = normalized(&value.url);
    let text = if label.is_empty() || label == url {
        url.clone()
    } else {
        format!("{label}: {url}")
    };
    paragraphs.push(Paragraph {
        kind: "link",
        text,
        url: Some(url),
    });
    Ok(())
}

fn paragraphs(document: &ResumeDocument) -> Result<Vec<Paragraph>, PdfRenderError> {
    ort_documents::render_plain_text(document).map_err(|_| PdfRenderError::InvalidContent)?;
    let mut out = Vec::new();
    add(&mut out, "name", &document.contact.full_name);
    for value in [
        &document.contact.email,
        &document.contact.phone,
        &document.contact.location,
    ] {
        add(&mut out, "text", value);
    }
    for value in &document.contact.links {
        link(&mut out, value)?;
    }
    for section in &document.sections {
        let mut entries = Vec::new();
        for entry in &section.entries {
            add(&mut entries, "entry", &entry.heading);
            for value in [&entry.subheading, &entry.date_range, &entry.location] {
                add(&mut entries, "text", value);
            }
            for field in &entry.fields {
                let value = normalized(&field.value);
                if !value.is_empty() {
                    let label = normalized(&field.label);
                    add(
                        &mut entries,
                        "text",
                        &if label.is_empty() {
                            value
                        } else {
                            format!("{label}: {value}")
                        },
                    );
                }
            }
            for bullet in &entry.bullets {
                add(&mut entries, "bullet", &bullet.text);
            }
            for value in &entry.links {
                link(&mut entries, value)?;
            }
        }
        if !entries.is_empty() {
            add(&mut out, "section", &section.heading);
            out.extend(entries);
        }
    }
    if out.len() > MAX_LAYOUT_BLOCKS
        || out
            .iter()
            .map(|p| p.text.matches('\n').count())
            .sum::<usize>()
            > MAX_HARD_BREAKS
    {
        return Err(PdfRenderError::LayoutLimit);
    }
    // Do not silently substitute missing characters. Check all selected faces:
    // headings and ordinary text must both have coverage. No system fallback.
    for c in out
        .iter()
        .flat_map(|p| p.text.chars())
        .filter(|c| !c.is_whitespace())
    {
        if FONTS
            .iter()
            .any(|font| !font.info().coverage.contains(u32::from(c)))
        {
            return Err(PdfRenderError::UnsupportedGlyph);
        }
    }
    Ok(out)
}

struct MemoryWorld {
    library: LazyHash<Library>,
    source: Source,
}

impl MemoryWorld {
    fn new(paragraphs: &[Paragraph]) -> Result<Self, PdfRenderError> {
        let json = serde_json::to_string(paragraphs).map_err(|_| PdfRenderError::InvalidContent)?;
        let mut inputs = Dict::new();
        inputs.insert("resume".into(), Value::Str(json.into()));
        Ok(Self {
            library: LazyHash::new(Library::builder().with_inputs(inputs).build()),
            source: SOURCE.clone(),
        })
    }
}

impl World for MemoryWorld {
    fn library(&self) -> &LazyHash<Library> {
        &self.library
    }
    fn book(&self) -> &LazyHash<FontBook> {
        &BOOK
    }
    fn main(&self) -> FileId {
        self.source.id()
    }
    fn source(&self, id: FileId) -> FileResult<Source> {
        if id == self.source.id() {
            Ok(self.source.clone())
        } else {
            Err(FileError::AccessDenied)
        }
    }
    fn file(&self, id: FileId) -> FileResult<Bytes> {
        if id == self.source.id() {
            Ok(Bytes::new(TEMPLATE.as_bytes()))
        } else {
            Err(FileError::AccessDenied)
        }
    }
    fn font(&self, index: usize) -> Option<Font> {
        FONTS.get(index).cloned()
    }
    fn today(&self, _offset: Option<Duration>) -> Option<Datetime> {
        None
    }
}

struct EvictMemoizedContent;
impl Drop for EvictMemoizedContent {
    fn drop(&mut self) {
        comemo::evict(0);
    }
}

#[must_use]
pub fn sha256(bytes: &[u8]) -> String {
    hex::encode(Sha256::digest(bytes))
}

// The reviewed template has only translated groups, text, links and tags.
// Reject overflow after layout (including very long unbreakable words), missing
// shaped glyphs, clipping, images or newly introduced drawing/transform behavior.
fn visible_frame(frame: &Frame, origin: Point, depth: usize) -> bool {
    if depth > 64 {
        return false;
    }
    frame.items().all(|(position, item)| {
        let point = origin + *position;
        match item {
            FrameItem::Group(group) => {
                group.clip.is_none()
                    && group.transform == Transform::identity()
                    && visible_frame(&group.frame, point, depth + 1)
            }
            FrameItem::Text(text) => {
                if text.glyphs.iter().any(|glyph| glyph.id == 0) {
                    return false;
                }
                if text.text.chars().all(char::is_whitespace) {
                    return true;
                }
                let bounds = text.bbox();
                [point + bounds.min, point + bounds.max]
                    .iter()
                    .all(|point| {
                        (55.0..=557.0).contains(&point.x.to_pt())
                            && (55.0..=737.0).contains(&point.y.to_pt())
                    })
            }
            FrameItem::Link(..) | FrameItem::Tag(..) => true,
            FrameItem::Image(..) | FrameItem::Shape(..) => false,
        }
    })
}

/// # Errors
/// Refuses invalid content, uncovered glyphs, layout/output limits, and compiler
/// warnings. Error messages never contain template diagnostics or resume text.
pub fn render_pdf(document: &ResumeDocument) -> Result<PdfArtifact, PdfRenderError> {
    let _guard = RENDER_LOCK
        .lock()
        .map_err(|_| PdfRenderError::Unavailable)?;
    let _eviction = EvictMemoizedContent;
    let content = paragraphs(document)?;
    let world = MemoryWorld::new(&content)?;
    let compiled = typst::compile::<typst_layout::PagedDocument>(&world);
    if !compiled.warnings.is_empty() {
        return Err(PdfRenderError::InvalidContent);
    }
    let output = compiled
        .output
        .map_err(|_| PdfRenderError::InvalidContent)?;
    if output.pages().is_empty() || output.pages().len() > MAX_PDF_PAGES {
        return Err(PdfRenderError::LayoutLimit);
    }
    if !output
        .pages()
        .iter()
        .all(|page| visible_frame(&page.frame, Point::zero(), 0))
    {
        return Err(PdfRenderError::LayoutLimit);
    }
    let bytes = typst_pdf::pdf(
        &output,
        &typst_pdf::PdfOptions {
            creator: Smart::Custom(None),
            ..Default::default()
        },
    )
    .map_err(|_| PdfRenderError::InvalidContent)?;
    if bytes.is_empty() || bytes.len() > MAX_PDF_BYTES {
        return Err(PdfRenderError::OutputTooLarge);
    }
    let mut font_hash = Sha256::new();
    for font in typst_assets::fonts().take(6) {
        font_hash.update(font);
    }
    let receipt = PdfRenderReceipt {
        document_sha256: sha256(
            &serde_json::to_vec(document).map_err(|_| PdfRenderError::InvalidContent)?,
        ),
        document_schema_version: document.schema_version,
        pdf_sha256: sha256(&bytes),
        renderer_version: RENDERER_VERSION.into(),
        template_id: TEMPLATE_ID.into(),
        template_sha256: sha256(TEMPLATE.as_bytes()),
        font_bundle_id: FONT_BUNDLE_ID.into(),
        font_bundle_sha256: hex::encode(font_hash.finalize()),
        page_count: output.pages().len(),
        byte_count: bytes.len(),
    };
    Ok(PdfArtifact { bytes, receipt })
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn bundled_template_compiles_without_warnings() {
        let _guard = RENDER_LOCK.lock().unwrap();
        let world = MemoryWorld::new(&[Paragraph {
            kind: "name",
            text: "Synthetic".into(),
            url: None,
        }])
        .unwrap();
        let result = typst::compile::<typst_layout::PagedDocument>(&world);
        assert!(result.warnings.is_empty(), "{:?}", result.warnings);
        assert!(result.output.is_ok(), "{:?}", result.output.err());
    }

    #[test]
    fn world_denies_external_files_packages_plugins_and_font_discovery() {
        let _guard = RENDER_LOCK.lock().unwrap();
        let mut world = MemoryWorld::new(&[]).unwrap();
        let other = typst::syntax::RootedPath::new(
            typst::syntax::VirtualRoot::Project,
            typst::syntax::VirtualPath::new("unavailable").unwrap(),
        )
        .intern();
        assert!(matches!(world.source(other), Err(FileError::AccessDenied)));
        assert!(matches!(world.file(other), Err(FileError::AccessDenied)));
        assert_eq!(FONTS.len(), 6);
        assert!(
            FONTS
                .iter()
                .all(|font| font.info().family == "Libertinus Serif")
        );
        assert!(world.font(6).is_none());
        assert!(world.today(None).is_none());
        for code in [
            r#"#read("/private/secret")"#,
            r#"#include "private.typ""#,
            r#"#import "@preview/unavailable:1.0.0": *"#,
            r#"#image("private.png")"#,
            r#"#plugin("private.wasm")"#,
        ] {
            world.source = Source::detached(code);
            assert!(
                typst::compile::<typst_layout::PagedDocument>(&world)
                    .output
                    .is_err()
            );
        }
    }
}
